(define-module (ebreak packages probe-rs-crates)
  #:use-module (guix packages)
  #:use-module (guix download)
  #:use-module (guix build-system cargo)
  #:export (lookup-cargo-inputs))

;;;
;;; This file is generated by ‘guix import crate probe-rs-tools
;;; --lockfile=...’ for probe-rs v0.32.0.  Do NOT add definitions manually.
;;;
;;; Rust libraries fetched from crates.io, pinned to the versions recorded
;;; in the upstream Cargo.lock of probe-rs v0.32.0.
;;;

(define qqqq-separator 'begin-of-crates)

(define rust-inflector-0.11.4
  (crate-source "Inflector" "0.11.4"
                "1lqmcni21ifzyq41fhz6k1j2b23cmsx469s4g4sf01l78miqqhzy"))

(define rust-addr2line-0.27.0
  (crate-source "addr2line" "0.27.0"
                "0sh8pyvyffgbc6bp2x71rz827xfk867h3ii537pm92lh86971qgg"))

(define rust-adler2-2.0.1
  (crate-source "adler2" "2.0.1"
                "1ymy18s9hs7ya1pjc9864l30wk8p2qfqdi7mhhcc5nfakxbij09j"))

(define rust-aho-corasick-1.1.4
  (crate-source "aho-corasick" "1.1.4"
                "00a32wb2h07im3skkikc495jvncf62jl6s96vwc7bhi70h9imlyx"))

(define rust-allocator-api2-0.2.21
  (crate-source "allocator-api2" "0.2.21"
                "08zrzs022xwndihvzdn78yqarv2b9696y67i6h78nla3ww87jgb8"))

(define rust-alterable-logger-1.0.1
  (crate-source "alterable_logger" "1.0.1"
                "17s1kf5wb0alcgs4q596izjbdlcj26hx3dy1vfp80i24f4hjj7vs"))

(define rust-android-system-properties-0.1.5
  (crate-source "android_system_properties" "0.1.5"
                "04b3wrz12837j7mdczqd95b732gw5q7q66cv4yn4646lvccp57l1"))

(define rust-ansi-parser-0.9.1
  (crate-source "ansi-parser" "0.9.1"
                "0wwicv3sx7sw3qhkkpjvnmynkpzc31b8bhj3s45ms0jg53c7ygn4"))

(define rust-ansi-width-0.1.0
  (crate-source "ansi-width" "0.1.0"
                "023693dwvci91456nfi0aygc44i1f098l2f23ssq67b1ybk3r7i1"))

(define rust-anstream-1.0.0
  (crate-source "anstream" "1.0.0"
                "13d2bj0xfg012s4rmq44zc8zgy1q8k9yp7yhvfnarscnmwpj2jl2"))

(define rust-anstyle-1.0.14
  (crate-source "anstyle" "1.0.14"
                "0030szmgj51fxkic1hpakxxgappxzwm6m154a3gfml83lq63l2wl"))

(define rust-anstyle-parse-1.0.0
  (crate-source "anstyle-parse" "1.0.0"
                "03hkv2690s0crssbnmfkr76kw1k7ah2i6s5amdy9yca2n8w7zkjj"))

(define rust-anstyle-query-1.1.5
  (crate-source "anstyle-query" "1.1.5"
                "1p6shfpnbghs6jsa0vnqd8bb8gd7pjd0jr7w0j8jikakzmr8zi20"))

(define rust-anstyle-wincon-3.0.11
  (crate-source "anstyle-wincon" "3.0.11"
                "0zblannm70sk3xny337mz7c6d8q8i24vhbqi42ld8v7q1wjnl7i9"))

(define rust-anyhow-1.0.103
  (crate-source "anyhow" "1.0.103"
                "1wsav2g6vxcvf2c0fv3jhxfr55l0p2g8nygy7rmmvcsfwgi8ahra"))

(define rust-approx-0.5.1
  (crate-source "approx" "0.5.1"
                "1ilpv3dgd58rasslss0labarq7jawxmivk17wsh8wmkdm3q15cfa"))

(define rust-arc-swap-1.7.1
  (crate-source "arc-swap" "1.7.1"
                "0mrl9a9r9p9bln74q6aszvf22q1ijiw089jkrmabfqkbj31zixv9"))

(define rust-arrayvec-0.7.7
  (crate-source "arrayvec" "0.7.7"
                "1zjxk501fc4lnkzkdicqsk7y3l3agw89ziqjzcjca6ry9n484a7h"))

(define rust-async-io-2.6.0
  (crate-source "async-io" "2.6.0"
                "1z16s18bm4jxlmp6rif38mvn55442yd3wjvdfhvx4hkgxf7qlss5"))

(define rust-atomic-0.6.1
  (crate-source "atomic" "0.6.1"
                "0h43ljcgbl6vk62hs6yk7zg7qn3myzvpw8k7isb9nzhkbdvvz758"))

(define rust-atomic-polyfill-1.0.3
  (crate-source "atomic-polyfill" "1.0.3"
                "1x00ndablb89zvbr8m03cgjzgajg86fqn8pgz85yy2gy1pivrwlc"))

(define rust-atomic-waker-1.1.2
  (crate-source "atomic-waker" "1.1.2"
                "1h5av1lw56m0jf0fd3bchxq8a30xv0b4wv8s4zkp4s0i7mfvs18m"))

(define rust-autocfg-1.5.0
  (crate-source "autocfg" "1.5.0"
                "1s77f98id9l4af4alklmzq46f21c980v13z2r1pcxx6bqgw0d1n0"))

(define rust-aws-lc-rs-1.17.0
  (crate-source "aws-lc-rs" "1.17.0"
                "003d69lq9qf12bj4j6csy3nrvilwa30yd9x9blx7h1f27vyg3hjy"))

(define rust-aws-lc-sys-0.41.0
  ;; TODO REVIEW: Check bundled sources.
  (crate-source "aws-lc-sys" "0.41.0"
                "1x735y1qny5v2gzpl928z1ppddb906nl1n8d2yv3mfc5rrwrfbqs"))

(define rust-axum-0.8.9
  (crate-source "axum" "0.8.9"
                "146df5x8dhczm1sp939gr3839220wl6rxc1k65bzc450z72ridii"))

(define rust-axum-core-0.5.5
  (crate-source "axum-core" "0.5.5"
                "08pa4752h96pai7j5avr2hnq35xh7qgv6vl57y1zhhnikkhnqi2r"))

(define rust-base64-0.22.1
  (crate-source "base64" "0.22.1"
                "1imqzgh7bxcikp5vx3shqvw9j09g9ly0xr0jma0q66i52r7jbcvj"))

(define rust-basic-udev-0.1.2
  (crate-source "basic-udev" "0.1.2"
                "1rmgw5flmld5lfxadagm7faf6lhgaazgzsz5wm6pg2pd3ivzjias"))

(define rust-bincode-2.0.1
  (crate-source "bincode" "2.0.1"
                "0h5pxp3dqkigjwy926a03sl69n9wv7aq4142a20kw9lhn3bzbsin"))

(define rust-bincode-derive-2.0.1
  (crate-source "bincode_derive" "2.0.1"
                "029wmh26hq3hhs1gq629y0frn2pkl7ld061rk23fji8g8jd715dz"))

(define rust-bitfield-0.19.4
  (crate-source "bitfield" "0.19.4"
                "06b4qjc40kgyv0a5cxfx4a7l6f5hcjmqgqb0pq4bzwmhqqbnbfi1"))

(define rust-bitfield-macros-0.19.4
  (crate-source "bitfield-macros" "0.19.4"
                "15qym2fxzj079hic6xibci256h8812s6nmkbzm2ipprg4776m3gl"))

(define rust-bitflags-1.3.2
  (crate-source "bitflags" "1.3.2"
                "12ki6w8gn1ldq7yz9y680llwk5gmrhrzszaa17g1sbrw2r2qvwxy"))

(define rust-bitflags-2.13.0
  (crate-source "bitflags" "2.13.0"
                "1y239gpvl061rfvav7jds8mjs42kmwi39is7yx5d1qw3hvp8nf5l"))

(define rust-bitmatch-0.1.1
  (crate-source "bitmatch" "0.1.1"
                "1bd3h49s3y4s0h5qhr1nr0yfc6p8z1y3p3jbb6scjrhrsh2y2lva"))

(define rust-bitvec-1.1.1
  (crate-source "bitvec" "1.1.1"
                "0dqq44v9877q0xbl4g6aaaf3xhh3m1ca7ag0iy4l17ap5k8w7knx"))

(define rust-block-buffer-0.10.4
  (crate-source "block-buffer" "0.10.4"
                "0w9sa2ypmrsqqvc20nhwr75wbb5cjr4kkyhpjm1z1lv2kdicfy1h"))

(define rust-block-buffer-0.12.0
  (crate-source "block-buffer" "0.12.0"
                "1glh8w49a7cj0wlkalyn9j605jzf2ss0lg8dqq5xh8cr2q451lyd"))

(define rust-boolean-expression-0.3.11
  (crate-source "boolean_expression" "0.3.11"
                "10zspcm7h2dsywi4d26h8crj10qf0mn2clnk5wjx58l18iifycvw"))

(define rust-bs58-0.5.1
  (crate-source "bs58" "0.5.1"
                "1x3v51n5n2s3l0rgrsn142akdf331n2qsa75pscw71fi848vm25z"))

(define rust-bumpalo-3.19.1
  (crate-source "bumpalo" "3.19.1"
                "044555i277xcinmqs7nnv8n5y4fqfi4l4lp1mp3i30vsidrxrnax"))

(define rust-by-address-1.2.1
  (crate-source "by_address" "1.2.1"
                "01idmag3lcwnnqrnnyik2gmbrr34drsi97q15ihvcbbidf2kryk4"))

(define rust-bytemuck-1.24.0
  (crate-source "bytemuck" "1.24.0"
                "1x65wc9kwf0dfnmglkl8r46d29pfl7yilll5wh9bcf0g6a0gbg8z"))

(define rust-bytemuck-derive-1.10.2
  (crate-source "bytemuck_derive" "1.10.2"
                "1zvmjmw1sdmx9znzm4dpbb2yvz9vyim8w6gp4z256l46qqdvvazr"))

(define rust-byteorder-1.5.0
  (crate-source "byteorder" "1.5.0"
                "0jzncxyf404mwqdbspihyzpkndfgda450l0893pz5xj685cg5l0z"))

(define rust-bytes-1.11.1
  (crate-source "bytes" "1.11.1"
                "0czwlhbq8z29wq0ia87yass2mzy1y0jcasjb8ghriiybnwrqfx0y"))

(define rust-bytesize-2.4.2
  (crate-source "bytesize" "2.4.2"
                "03n5bxzj2lv9hxwc6n1hh8rhismvkd85ampx5y9v4rwjjqc8jz1x"))

(define rust-camino-1.2.2
  (crate-source "camino" "1.2.2"
                "0j0ayqfbbl8bxg0795ssk1hzkjix3dvl2kk63hdgzf9cd5nscag6"))

(define rust-capstone-0.14.0
  (crate-source "capstone" "0.14.0"
                "1m0xxf19cvdfdwys5brb0zx1r766jmn3i9dl6hrr46rz5w7swhpl"))

(define rust-capstone-sys-0.18.0
  ;; TODO REVIEW: Check bundled sources.
  (crate-source "capstone-sys" "0.18.0"
                "01dciarlv3wdr7kv5ai8lk9l2kxsi4lxharab9gjjcb7mdy0is54"))

(define rust-cargo-config2-0.1.44
  (crate-source "cargo-config2" "0.1.44"
                "0dxdzaw19aib7bx05fsg3ia3frg76izy3mrpzf281irrfczsbb95"))

(define rust-cargo-platform-0.3.2
  (crate-source "cargo-platform" "0.3.2"
                "10k0bvf5lnsndqgd92qxx3a2lask5nh2w2k568gz04cg2kkc1847"))

(define rust-cargo-metadata-0.23.1
  (crate-source "cargo_metadata" "0.23.1"
                "1sddycfscjy47av3ykzykqgz8zjds0i00gcxs76vw4x1n0bpv67g"))

(define rust-castaway-0.2.4
  (crate-source "castaway" "0.2.4"
                "0nn5his5f8q20nkyg1nwb40xc19a08yaj4y76a8q2y3mdsmm3ify"))

(define rust-cbor-edn-0.0.6
  (crate-source "cbor-edn" "0.0.6"
                "0y4jqs8ghj9qqggrxq4zfkb826p7yr72wg2rm251clzkn4lkid59"))

(define rust-cc-1.2.50
  (crate-source "cc" "1.2.50"
                "0g1q2k30bwnym5hlhk2y3k08hhrklgn68gr61b63f73s49ixal4z"))

(define rust-cfg-if-1.0.4
  (crate-source "cfg-if" "1.0.4"
                "008q28ajc546z5p2hcwdnckmg0hia7rnx52fni04bwqkzyrghc4k"))

(define rust-cfg-aliases-0.2.1
  (crate-source "cfg_aliases" "0.2.1"
                "092pxdc1dbgjb6qvh83gk56rkic2n2ybm4yvy76cgynmzi3zwfk1"))

(define rust-chacha20-0.10.1
  (crate-source "chacha20" "0.10.1"
                "108aajbvs3rwl4d0pdvq3p8ydy4pwh0rxy2z265ynwkflrmla96m"))

(define rust-chrono-0.4.42
  (crate-source "chrono" "0.4.42"
                "1lp8iz9js9jwxw0sj8yi59v54lgvwdvm49b9wch77f25sfym4l0l"))

(define rust-clap-4.6.2
  (crate-source "clap" "4.6.2"
                "04ah42lfd7imr2mqj7xh0xgk3k5imb63hpgnhwvnphzmljfry1fx"))

(define rust-clap-builder-4.6.2
  (crate-source "clap_builder" "4.6.2"
                "12sl6fyj6w2djxj0lsc1lkj1h3wpx74fjhb37izvaf65vjpji5ph"))

(define rust-clap-complete-4.6.7
  (crate-source "clap_complete" "4.6.7"
                "0yq2xmvm93l4lbaf3xnacy1rph5zwjlwlvrxzxhh2pqq31wkk2yv"))

(define rust-clap-derive-4.6.1
  (crate-source "clap_derive" "4.6.1"
                "1acpz49hi00iv9jkapixjzcv7s51x8qkfaqscjm36rqgf428dkpj"))

(define rust-clap-lex-1.0.0
  (crate-source "clap_lex" "1.0.0"
                "0c8888qi1l9sayqlv666h8s0yxn2qc6jr88v1zagk43mpjjjx0is"))

(define rust-cmake-0.1.58
  (crate-source "cmake" "0.1.58"
                "0y06zxw5sv1p5vvpp5rz1qwbrq7ccawrl09nqy5ahx1a5418mxy0"))

(define rust-cmsis-pack-0.7.2
  (crate-source "cmsis-pack" "0.7.2"
                "0i0s3slskz1k9hqvkr77kipf347al91bky3glgyqfx4m15v7h74s"))

(define rust-cobs-0.3.0
  (crate-source "cobs" "0.3.0"
                "18f0kxxa1fqb8pz2dxwssnhsrvhrs5j4p8xllgin5d7h36sn3a8g"))

(define rust-cobs-0.5.1
  (crate-source "cobs" "0.5.1"
                "1gilq15pmdkhlq2zwx13canjl4n12jfvv78c8hqd1b173cngv4yx"))

(define rust-colorchoice-1.0.4
  (crate-source "colorchoice" "1.0.4"
                "0x8ymkz1xr77rcj1cfanhf416pc4v681gmkc9dzb3jqja7f62nxh"))

(define rust-colored-2.2.0
  (crate-source "colored" "2.2.0"
                "0g6s7j2qayjd7i3sivmwiawfdg8c8ldy0g2kl4vwk1yk16hjaxqi"))

(define rust-colored-3.1.1
  (crate-source "colored" "3.1.1"
                "0d5cpbgvyvmmky199s885s6385ykd75q6qg3d2kcxjxq563ldygs"))

(define rust-combine-4.6.7
  (crate-source "combine" "4.6.7"
                "1z8rh8wp59gf8k23ar010phgs0wgf5i8cx4fg01gwcnzfn5k0nms"))

(define rust-compact-str-0.9.0
  (crate-source "compact_str" "0.9.0"
                "0ykhh2scg32lmzxak107pmby6fmnz7qbhsi9i8g9iknfl4ji7nrz"))

(define rust-concurrent-queue-2.5.0
  (crate-source "concurrent-queue" "2.5.0"
                "0wrr3mzq2ijdkxwndhf79k952cp4zkz35ray8hvsxl96xrx1k82c"))

(define rust-console-0.16.4
  (crate-source "console" "0.16.4"
                "0z5sik90c39ywvkdkdc5bqrkbj441ycmvf21mn7yizpnlijz9rag"))

(define rust-const-oid-0.10.2
  (crate-source "const-oid" "0.10.2"
                "0p7m286mp8aai4sa72g7ji6qm0d4ns8wg4i4b2hj9p9615zm3vx6"))

(define rust-convert-case-0.10.0
  (crate-source "convert_case" "0.10.0"
                "1fff1x78mp2c233g68my0ag0zrmjdbym8bfyahjbfy4cxza5hd33"))

(define rust-cordyceps-0.3.4
  (crate-source "cordyceps" "0.3.4"
                "0aharq07vlfjia6jxkkf0322n7y3r0v6ylzjbrvxxf4jh2xpz3b8"))

(define rust-core-foundation-0.10.1
  (crate-source "core-foundation" "0.10.1"
                "1xjns6dqf36rni2x9f47b65grxwdm20kwdg9lhmzdrrkwadcv9mj"))

(define rust-core-foundation-sys-0.8.7
  ;; TODO REVIEW: Check bundled sources.
  (crate-source "core-foundation-sys" "0.8.7"
                "12w8j73lazxmr1z0h98hf3z623kl8ms7g07jch7n4p8f9nwlhdkp"))

(define rust-cpp-demangle-0.5.1
  (crate-source "cpp_demangle" "0.5.1"
                "1vwx8a999mpqywx0736v54909y52x77w1myjsr6cnmpa69630rq6"))

(define rust-cpufeatures-0.2.17
  (crate-source "cpufeatures" "0.2.17"
                "10023dnnaghhdl70xcds12fsx2b966sxbxjq5sxs49mvxqw5ivar"))

(define rust-cpufeatures-0.3.0
  (crate-source "cpufeatures" "0.3.0"
                "00fjhygsqmh4kbxxlb99mcsbspxcai6hjydv4c46pwb67wwl2alb"))

(define rust-crc32fast-1.5.0
  (crate-source "crc32fast" "1.5.0"
                "04d51liy8rbssra92p0qnwjw8i9rm9c4m3bwy19wjamz1k4w30cl"))

(define rust-critical-section-1.2.0
  (crate-source "critical-section" "1.2.0"
                "02ylhcykxjc40xrfhk1lwc21jqgz4dbwv3jr49ymw733c51yl3kr"))

(define rust-crossbeam-channel-0.5.15
  (crate-source "crossbeam-channel" "0.5.15"
                "1cicd9ins0fkpfgvz9vhz3m9rpkh6n8d3437c3wnfsdkd3wgif42"))

(define rust-crossbeam-utils-0.8.21
  (crate-source "crossbeam-utils" "0.8.21"
                "0a3aa2bmc8q35fb67432w16wvi54sfmb69rk9h5bhd18vw0c99fh"))

(define rust-crossterm-0.29.0
  (crate-source "crossterm" "0.29.0"
                "0yzqxxd90k7d2ac26xq1awsznsaq0qika2nv1ik3p0vzqvjg5ffq"))

(define rust-crossterm-winapi-0.9.1
  (crate-source "crossterm_winapi" "0.9.1"
                "0axbfb2ykbwbpf1hmxwpawwfs8wvmkcka5m561l7yp36ldi7rpdc"))

(define rust-crypto-common-0.1.7
  (crate-source "crypto-common" "0.1.7"
                "02nn2rhfy7kvdkdjl457q2z0mklcvj9h662xrq6dzhfialh2kj3q"))

(define rust-crypto-common-0.2.1
  (crate-source "crypto-common" "0.2.1"
                "041p8bs680hrg6rhicfifn19cfvybq9aya5i4i0k08d9byqpnwkp"))

(define rust-csv-1.4.0
  (crate-source "csv" "1.4.0"
                "0f7r2ip0rbi7k377c3xmsh9xd69sillffhpfmbgnvz3yrxl9vkaj"))

(define rust-csv-core-0.1.13
  (crate-source "csv-core" "0.1.13"
                "10lppd3fdb1i5npgx9xqjs5mjmy2qbdi8n16i48lg03ak4k3qjkh"))

(define rust-darling-0.20.11
  (crate-source "darling" "0.20.11"
                "1vmlphlrlw4f50z16p4bc9p5qwdni1ba95qmxfrrmzs6dh8lczzw"))

(define rust-darling-core-0.20.11
  (crate-source "darling_core" "0.20.11"
                "0bj1af6xl4ablnqbgn827m43b8fiicgv180749f5cphqdmcvj00d"))

(define rust-darling-macro-0.20.11
  (crate-source "darling_macro" "0.20.11"
                "1bbfbc2px6sj1pqqq97bgqn6c8xdnb2fmz66f7f40nrqrcybjd7w"))

(define rust-data-encoding-2.9.0
  (crate-source "data-encoding" "2.9.0"
                "0xm46371aw613ghc12ay4vsnn49hpcmcwlijnqy8lbp2bpd308ra"))

(define rust-data-encoding-macro-0.1.18
  (crate-source "data-encoding-macro" "0.1.18"
                "0gb7xr2a7gg62bfmkg32kvcwhnmx24v6i1d1488z00h1xab6rkj7"))

(define rust-data-encoding-macro-internal-0.1.16
  (crate-source "data-encoding-macro-internal" "0.1.16"
                "0xhrbiib486iggdzlcmpi13xvd7dqdd4zacdi940b6d6vbp2n5ld"))

(define rust-debugid-0.8.0
  (crate-source "debugid" "0.8.0"
                "13f15dfvn07fa7087pmacixqqv0lmj4hv93biw4ldr48ypk55xdy"))

(define rust-deflate64-0.1.10
  (crate-source "deflate64" "0.1.10"
                "012jmx4jrxwdk5d6fbnnxih4zdq9nb0vmjzhqasjkvf5a71qzgr6"))

(define rust-defmt-decoder-1.1.0
  (crate-source "defmt-decoder" "1.1.0"
                "1llnj600hwqcf4jvw2va7nkv2hyb4ym7biczzszlc3gp6g02f14y"))

(define rust-defmt-json-schema-0.1.0
  (crate-source "defmt-json-schema" "0.1.0"
                "0smd5mxzk3b6j82ykb0fzk34f6xl1fcchsyqhprir9jpiqi4vc4n"))

(define rust-defmt-parser-1.0.0
  (crate-source "defmt-parser" "1.0.0"
                "0gpfky9sssil5qfaix5wxcwiqk7snszhl5gq3vcwkrxjncs07mhh"))

(define rust-deku-0.18.1
  (crate-source "deku" "0.18.1"
                "1sznandp5jck1cs80xar26wwgm4p8cxkd1b9sq317p09w8qi0wd9"))

(define rust-deku-derive-0.18.1
  (crate-source "deku_derive" "0.18.1"
                "178k9wdlaay2jqvvnx4swg1wq8hd5z74lhs0zf0lxgiwb0chgjsq"))

(define rust-deranged-0.5.8
  (crate-source "deranged" "0.5.8"
                "0711df3w16vx80k55ivkwzwswziinj4dz05xci3rvmn15g615n3w"))

(define rust-derive-more-2.1.1
  (crate-source "derive_more" "2.1.1"
                "0d5i10l4aff744jw7v4n8g6cv15rjk5mp0f1z522pc2nj7jfjlfp"))

(define rust-derive-more-impl-2.1.1
  (crate-source "derive_more-impl" "2.1.1"
                "1jwdp836vymp35d7mfvvalplkdgk2683nv3zjlx65n1194k9g6kr"))

(define rust-diff-0.1.13
  (crate-source "diff" "0.1.13"
                "1j0nzjxci2zqx63hdcihkp0a4dkdmzxd7my4m7zk6cjyfy34j9an"))

(define rust-digest-0.10.7
  (crate-source "digest" "0.10.7"
                "14p2n6ih29x81akj097lvz7wi9b6b9hvls0lwrv7b6xwyy0s5ncy"))

(define rust-digest-0.11.2
  (crate-source "digest" "0.11.2"
                "0g0m77q7zfafm4jgy6i70wwimy9f41ywidbz9w467rh8px4xnl28"))

(define rust-directories-6.0.0
  (crate-source "directories" "6.0.0"
                "0zgy2w088v8w865c11dmc3dih899fgrhvrfp7g83h6v6ai60kx8n"))

(define rust-dirs-sys-0.5.0
  ;; TODO REVIEW: Check bundled sources.
  (crate-source "dirs-sys" "0.5.0"
                "1aqzpgq6ampza6v012gm2dppx9k35cdycbj54808ksbys9k366p0"))

(define rust-displaydoc-0.2.5
  (crate-source "displaydoc" "0.2.5"
                "1q0alair462j21iiqwrr21iabkfnb13d6x5w95lkdg21q2xrqdlp"))

(define rust-dissimilar-1.0.10
  (crate-source "dissimilar" "1.0.10"
                "08b94x25x3ba6vg79i53wspxyagqr43crg9dw2zn2dpgl3dgyxc9"))

(define rust-docsplay-0.1.3
  (crate-source "docsplay" "0.1.3"
                "1d7sb1kq07h6jn82c0hsvimi7l87drgcxz4nfyfvpib2vf0fliw5"))

(define rust-docsplay-macros-0.1.2
  (crate-source "docsplay-macros" "0.1.2"
                "1p8zlxc82a077wz156y1c9zma6krbbgymazk4vc29c9xxg9jwxqi"))

(define rust-document-features-0.2.12
  (crate-source "document-features" "0.2.12"
                "0qcgpialq3zgvjmsvar9n6v10rfbv6mk6ajl46dd4pj5hn3aif6l"))

(define rust-dunce-1.0.5
  (crate-source "dunce" "1.0.5"
                "04y8wwv3vvcqaqmqzssi6k0ii9gs6fpz96j5w9nky2ccsl23axwj"))

(define rust-either-1.15.0
  (crate-source "either" "1.15.0"
                "069p1fknsmzn9llaizh77kip0pqmcwpdsykv2x30xpjyija5gis8"))

(define rust-embedded-io-0.4.0
  (crate-source "embedded-io" "0.4.0"
                "1v9wrc5nsgaaady7i3ya394sik5251j0iq5rls7mrx7fv696h6pg"))

(define rust-embedded-io-0.6.1
  (crate-source "embedded-io" "0.6.1"
                "0v901xykajh3zffn6x4cnn4fhgfw3c8qpjwbsk6gai3gaccg3l7d"))

(define rust-encode-unicode-0.3.6
  (crate-source "encode_unicode" "0.3.6"
                "07w3vzrhxh9lpjgsg2y5bwzfar2aq35mdznvcp3zjl0ssj7d4mx3"))

(define rust-encode-unicode-1.0.0
  (crate-source "encode_unicode" "1.0.0"
                "1h5j7j7byi289by63s3w4a8b3g6l5ccdrws7a67nn07vdxj77ail"))

(define rust-encoding-rs-0.8.35
  (crate-source "encoding_rs" "0.8.35"
                "1wv64xdrr9v37rqqdjsyb8l8wzlcbab80ryxhrszvnj59wy0y0vm"))

(define rust-env-filter-2.0.0
  (crate-source "env_filter" "2.0.0"
                "05s267np8pphhpxzrzl4j956gjj87f4ik6yas7l1x6kr0cd2f3ch"))

(define rust-env-logger-0.11.11
  (crate-source "env_logger" "0.11.11"
                "1xnkbhnlwf45a6val2340bi7avi7fwgbm2g2kbf9g9vmgb91nryy"))

(define rust-equivalent-1.0.2
  (crate-source "equivalent" "1.0.2"
                "03swzqznragy8n0x31lqc78g2af054jwivp7lkrbrc0khz74lyl7"))

(define rust-errno-0.3.14
  (crate-source "errno" "0.3.14"
                "1szgccmh8vgryqyadg8xd58mnwwicf39zmin3bsn63df2wbbgjir"))

(define rust-escape8259-0.5.3
  (crate-source "escape8259" "0.5.3"
                "1in2zrdak794x8v11lkrrgyqxjjqbijvg0yfn2paay0rb9xxv4jn"))

(define rust-esp-idf-part-0.6.0
  (crate-source "esp-idf-part" "0.6.0"
                "0qabz7jdnjlvw04snqa9ndddqi5dskyc6m1m324lw3h33lwc5szm"))

(define rust-espflash-4.5.0
  (crate-source "espflash" "4.5.0"
                "0cli942piqq4mfn78agq5f1hb7c9d35ijvpjs2qy3hhaf711yrgm"))

(define rust-fallible-iterator-0.3.0
  (crate-source "fallible-iterator" "0.3.0"
                "0ja6l56yka5vn4y4pk6hn88z0bpny7a8k1919aqjzp0j1yhy9k1a"))

(define rust-fast-srgb8-1.0.0
  (crate-source "fast-srgb8" "1.0.0"
                "18g6xwwh4gnkyx1352hnvwagpv0n4y98yp2llm8vyvwxh487abnx"))

(define rust-fastrand-2.4.1
  (crate-source "fastrand" "2.4.1"
                "1mnqxxnxvd69ma9mczabpbbsgwlhd6l78yv3vd681453a9s247wz"))

(define rust-figment-0.10.19
  (crate-source "figment" "0.10.19"
                "1ww9sxdzjj2i80w7bq0kllnymjyrfb1cdx2h70ap5wqcdga1rc4c"))

(define rust-find-msvc-tools-0.1.5
  (crate-source "find-msvc-tools" "0.1.5"
                "0i1ql02y37bc7xywkqz10kx002vpz864vc4qq88h1jam190pcc1s"))

(define rust-flate2-1.1.9
  (crate-source "flate2" "1.1.9"
                "0g2pb7cxnzcbzrj8bw4v6gpqqp21aycmf6d84rzb6j748qkvlgw4"))

(define rust-fnv-1.0.7
  (crate-source "fnv" "1.0.7"
                "1hc2mcqha06aibcaza94vbi81j6pr9a1bbxrxjfhc91zin8yr7iz"))

(define rust-foldhash-0.2.0
  (crate-source "foldhash" "0.2.0"
                "1nvgylb099s11xpfm1kn2wcsql080nqmnhj1l25bp3r2b35j9kkp"))

(define rust-form-urlencoded-1.2.2
  (crate-source "form_urlencoded" "1.2.2"
                "1kqzb2qn608rxl3dws04zahcklpplkd5r1vpabwga5l50d2v4k6b"))

(define rust-fs-extra-1.3.0
  (crate-source "fs_extra" "1.3.0"
                "075i25z70j2mz9r7i9p9r521y8xdj81q7skslyb7zhqnnw33fw22"))

(define rust-funty-2.0.0
  (crate-source "funty" "2.0.0"
                "177w048bm0046qlzvp33ag3ghqkqw4ncpzcm5lq36gxf2lla7mg6"))

(define rust-futures-0.3.32
  (crate-source "futures" "0.3.32"
                "0b9q86r5ar18v5xjiyqn7sb8sa32xv98qqnfz779gl7ns7lpw54b"))

(define rust-futures-channel-0.3.32
  (crate-source "futures-channel" "0.3.32"
                "07fcyzrmbmh7fh4ainilf1s7gnwvnk07phdq77jkb9fpa2ffifq7"))

(define rust-futures-core-0.3.32
  (crate-source "futures-core" "0.3.32"
                "07bbvwjbm5g2i330nyr1kcvjapkmdqzl4r6mqv75ivvjaa0m0d3y"))

(define rust-futures-executor-0.3.32
  (crate-source "futures-executor" "0.3.32"
                "17aplz3ns74qn7a04qg7qlgsdx5iwwwkd4jvdfra6hl3h4w9rwms"))

(define rust-futures-io-0.3.32
  (crate-source "futures-io" "0.3.32"
                "063pf5m6vfmyxj74447x8kx9q8zj6m9daamj4hvf49yrg9fs7jyf"))

(define rust-futures-lite-2.6.1
  (crate-source "futures-lite" "2.6.1"
                "1ba4dg26sc168vf60b1a23dv1d8rcf3v3ykz2psb7q70kxh113pp"))

(define rust-futures-macro-0.3.32
  (crate-source "futures-macro" "0.3.32"
                "0ys4b1lk7s0bsj29pv42bxsaavalch35rprp64s964p40c1bfdg8"))

(define rust-futures-sink-0.3.32
  (crate-source "futures-sink" "0.3.32"
                "14q8ml7hn5a6gyy9ri236j28kh0svqmrk4gcg0wh26rkazhm95y3"))

(define rust-futures-task-0.3.32
  (crate-source "futures-task" "0.3.32"
                "14s3vqf8llz3kjza33vn4ixg6kwxp61xrysn716h0cwwsnri2xq3"))

(define rust-futures-util-0.3.32
  (crate-source "futures-util" "0.3.32"
                "1mn60lw5kh32hz9isinjlpw34zx708fk5q1x0m40n6g6jq9a971q"))

(define rust-fxprof-processed-profile-0.8.1
  (crate-source "fxprof-processed-profile" "0.8.1"
                "0mx5xnbx8ph2zy6asx74lqlvag7hxhwzw33pc4m9c2pclch4y8r5"))

(define rust-gdbstub-0.7.8
  (crate-source "gdbstub" "0.7.8"
                "0gsz4x71gmaq1qh2k14k708nvfil6gfx086mlpwcl0jr74mjsx3j"))

(define rust-generator-0.8.8
  (crate-source "generator" "0.8.8"
                "1ybcxxz9vdh7nyh9q5654zv5q790b63a83w0zrv0r8id2pj4mw2j"))

(define rust-generic-array-0.14.7
  (crate-source "generic-array" "0.14.7"
                "16lyyrzrljfq424c3n8kfwkqihlimmsg5nhshbbp48np3yjrqr45"))

(define rust-getrandom-0.2.16
  (crate-source "getrandom" "0.2.16"
                "14l5aaia20cc6cc08xdlhrzmfcylmrnprwnna20lqf746pqzjprk"))

(define rust-getrandom-0.3.4
  (crate-source "getrandom" "0.3.4"
                "1zbpvpicry9lrbjmkd4msgj3ihff1q92i334chk7pzf46xffz7c9"))

(define rust-getrandom-0.4.3
  (crate-source "getrandom" "0.4.3"
                "16b0202fkdwz3p2cyll82dv24ljbn0wiyy829v4lwbkbflyqh3ih"))

(define rust-gimli-0.29.0
  (crate-source "gimli" "0.29.0"
                "1zgzprnjaawmg6zyic4f2q2hc39kdhn116qnkqpgvsasgc3x9v20"))

(define rust-gimli-0.32.3
  (crate-source "gimli" "0.32.3"
                "1iqk5xznimn5bfa8jy4h7pa1dv3c624hzgd2dkz8mpgkiswvjag6"))

(define rust-gimli-0.34.0
  (crate-source "gimli" "0.34.0"
                "047xmabk4x75a2i47m860d7z9p8bryrbz5jk7di1iia9ngqclcqh"))

(define rust-git-version-0.3.9
  (crate-source "git-version" "0.3.9"
                "06ddi3px6l2ip0srn8512bsh8wrx4rzi65piya0vrz5h7nm6im8s"))

(define rust-git-version-macro-0.3.9
  (crate-source "git-version-macro" "0.3.9"
                "1h1s08fgh9bkwnc2hmjxcldv69hlxpq7a09cqdxsd5hb235hq0ak"))

(define rust-glob-0.3.3
  (crate-source "glob" "0.3.3"
                "106jpd3syfzjfj2k70mwm0v436qbx96wig98m4q8x071yrq35hhc"))

(define rust-goblin-0.10.7
  (crate-source "goblin" "0.10.7"
                "1j542pyn5whjaxlqb6lb3b0sxi67fr5573n1rracm33ilwb2cn0p"))

(define rust-gpiocdev-0.8.0
  (crate-source "gpiocdev" "0.8.0"
                "18b0fri5kwwncmdlbhp9wjp9xs3s6nfkfgckynkn5pb6czphjq2a"))

(define rust-gpiocdev-uapi-0.7.0
  (crate-source "gpiocdev-uapi" "0.7.0"
                "18z92d5wvwdlk69a7n9vwpl8ywg7lp3qwwryldaq4w7g0v73l6nb"))

(define rust-hash32-0.2.1
  (crate-source "hash32" "0.2.1"
                "0rrbv5pc5b1vax6j6hk7zvlrpw0h6aybshxy9vbpgsrgfrc5zhxh"))

(define rust-hash32-0.3.1
  (crate-source "hash32" "0.3.1"
                "01h68z8qi5gl9lnr17nz10lay8wjiidyjdyd60kqx8ibj090pmj7"))

(define rust-hashbrown-0.16.1
  (crate-source "hashbrown" "0.16.1"
                "004i3njw38ji3bzdp9z178ba9x3k0c1pgy8x69pj7yfppv4iq7c4"))

(define rust-hashbrown-0.17.0
  (crate-source "hashbrown" "0.17.0"
                "0l8gvcz80lvinb7x22h53cqbi2y1fm603y2jhhh9qwygvkb7sijg"))

(define rust-heapless-0.7.17
  (crate-source "heapless" "0.7.17"
                "0kwn2wzk9fnsqnwp6rqjqhvh6hfq4rh225xwqjm72b5n1ry4bind"))

(define rust-heapless-0.8.0
  (crate-source "heapless" "0.8.0"
                "1b9zpdjv4qkl2511s2c80fz16fx9in4m9qkhbaa8j73032v9xyqb"))

(define rust-heapless-0.9.2
  (crate-source "heapless" "0.9.2"
                "1vc9rp0swh5msr964c9vrcxl8v8qf15qqxmim69b5ckxfmglbwia"))

(define rust-heck-0.5.0
  (crate-source "heck" "0.5.0"
                "1sjmpsdl8czyh9ywl3qcsfsq9a307dg4ni2vnlwgnzzqhc4y0113"))

(define rust-hermit-abi-0.5.2
  (crate-source "hermit-abi" "0.5.2"
                "1744vaqkczpwncfy960j2hxrbjl1q01csm84jpd9dajbdr2yy3zw"))

(define rust-hex-0.4.3
  (crate-source "hex" "0.4.3"
                "0w1a4davm1lgzpamwnba907aysmlrnygbqmfis2mqjx5m552a93z"))

(define rust-hexdump-0.1.3
  (crate-source "hexdump" "0.1.3"
                "04rrmf4y2dc75wa09ayiisinhnglq47pvh4n9061599sxqcjarxw"))

(define rust-hexfloat2-0.1.3
  (crate-source "hexfloat2" "0.1.3"
                "134znh5pjgh798r6xdz2pxpqb38rqc71mlp0yv6l200998b6bzmy"))

(define rust-hidapi-2.6.6
  (crate-source "hidapi" "2.6.6"
                "1s8hn389ipkph9f29vxrrqvhg4rvadj7x2f3r8zvqrgq2byav3f7"))

(define rust-http-1.4.0
  (crate-source "http" "1.4.0"
                "06iind4cwsj1d6q8c2xgq8i2wka4ps74kmws24gsi1bzdlw2mfp3"))

(define rust-http-body-1.0.1
  (crate-source "http-body" "1.0.1"
                "111ir5k2b9ihz5nr9cz7cwm7fnydca7dx4hc7vr16scfzghxrzhy"))

(define rust-http-body-util-0.1.3
  (crate-source "http-body-util" "0.1.3"
                "0jm6jv4gxsnlsi1kzdyffjrj8cfr3zninnxpw73mvkxy4qzdj8dh"))

(define rust-httparse-1.10.1
  (crate-source "httparse" "1.10.1"
                "11ycd554bw2dkgw0q61xsa7a4jn1wb1xbfacmf3dbwsikvkkvgvd"))

(define rust-httpdate-1.0.3
  (crate-source "httpdate" "1.0.3"
                "1aa9rd2sac0zhjqh24c9xvir96g188zldkx0hr6dnnlx5904cfyz"))

(define rust-hybrid-array-0.4.10
  (crate-source "hybrid-array" "0.4.10"
                "055jvmp7rsb44z5aimj9zbam9y33nplyagik38m0xd36yy6cyi1r"))

(define rust-hyper-1.8.1
  (crate-source "hyper" "1.8.1"
                "04cxr8j5y86bhxxlyqb8xkxjskpajk7cxwfzzk4v3my3a3rd9cia"))

(define rust-hyper-rustls-0.27.7
  (crate-source "hyper-rustls" "0.27.7"
                "0n6g8998szbzhnvcs1b7ibn745grxiqmlpg53xz206v826v3xjg3"))

(define rust-hyper-util-0.1.19
  (crate-source "hyper-util" "0.1.19"
                "0pyzc8378baf996l5ycl4y0s3skhxc4z4vkah9mvff3r1vb0ay3j"))

(define rust-iana-time-zone-0.1.64
  (crate-source "iana-time-zone" "0.1.64"
                "1yz980fmhaq9bdkasz35z63az37ci6kzzfhya83kgdqba61pzr9k"))

(define rust-iana-time-zone-haiku-0.1.2
  (crate-source "iana-time-zone-haiku" "0.1.2"
                "17r6jmj31chn7xs9698r122mapq85mfnv98bb4pg6spm0si2f67k"))

(define rust-icu-collections-2.1.1
  (crate-source "icu_collections" "2.1.1"
                "0hsblchsdl64q21qwrs4hvc2672jrf466zivbj1bwyv606bn8ssc"))

(define rust-icu-locale-core-2.1.1
  (crate-source "icu_locale_core" "2.1.1"
                "1djvdc2f5ylmp1ymzv4gcnmq1s4hqfim9nxlcm173lsd01hpifpd"))

(define rust-icu-normalizer-2.1.1
  (crate-source "icu_normalizer" "2.1.1"
                "16dmn5596la2qm0r3vih0bzjfi0vx9a20yqjha6r1y3vnql8hv2z"))

(define rust-icu-normalizer-data-2.1.1
  (crate-source "icu_normalizer_data" "2.1.1"
                "02jnzizg6q75m41l6c13xc7nkc5q8yr1b728dcgfhpzw076wrvbs"))

(define rust-icu-properties-2.1.2
  (crate-source "icu_properties" "2.1.2"
                "1v3lbmhhi7i6jgw51ikjb1p50qh5rb67grlkdnkc63l7zq1gq2q2"))

(define rust-icu-properties-data-2.1.2
  (crate-source "icu_properties_data" "2.1.2"
                "1bvpkh939rgzrjfdb7hz47v4wijngk0snmcgrnpwc9fpz162jv31"))

(define rust-icu-provider-2.1.1
  (crate-source "icu_provider" "2.1.1"
                "0576b7dizgyhpfa74kacv86y4g1p7v5ffd6c56kf1q82rvq2r5l5"))

(define rust-ident-case-1.0.1
  (crate-source "ident_case" "1.0.1"
                "0fac21q6pwns8gh1hz3nbq15j8fi441ncl6w4vlnd1cmc55kiq5r"))

(define rust-idna-1.1.0
  (crate-source "idna" "1.1.0"
                "1pp4n7hppm480zcx411dsv9wfibai00wbpgnjj4qj0xa7kr7a21v"))

(define rust-idna-adapter-1.2.1
  (crate-source "idna_adapter" "1.2.1"
                "0i0339pxig6mv786nkqcxnwqa87v4m94b2653f6k3aj0jmhfkjis"))

(define rust-ihex-3.0.0
  (crate-source "ihex" "3.0.0"
                "1wlzfyy5fsqgpki5vdapw0jjczqdm6813fgd3661wf5vfi3phnin"))

(define rust-indexmap-2.14.0
  (crate-source "indexmap" "2.14.0"
                "1na9z6f0d5pkjr1lgsni470v98gv2r7c41j8w48skr089x2yjrnl"))

(define rust-indicatif-0.18.6
  (crate-source "indicatif" "0.18.6"
                "037vk2cr5b0iwri5023wjyww7d4gqpjcf8f0g6x1mv5lsrn80cwl"))

(define rust-indoc-2.0.7
  (crate-source "indoc" "2.0.7"
                "01np60qdq6lvgh8ww2caajn9j4dibx9n58rvzf7cya1jz69mrkvr"))

(define rust-inlinable-string-0.1.15
  (crate-source "inlinable_string" "0.1.15"
                "1ysjci8yfvxgf51z0ny2nnwhxrclhmb3vbngin8v4bznhr3ybyn8"))

(define rust-insta-1.48.0
  (crate-source "insta" "1.48.0"
                "10kbxza7vzj4nvkga8r3rfn6z8i3hnh47bnnb1f429n9x3zgiw46"))

(define rust-instability-0.3.10
  (crate-source "instability" "0.3.10"
                "170dsap2il7fpx85dylb4q979czrbj77ay6v77vpvvpgdqcv0y37"))

(define rust-io-kit-sys-0.4.1
  ;; TODO REVIEW: Check bundled sources.
  (crate-source "io-kit-sys" "0.4.1"
                "0ysy5k3wf54yangy25hkj10xx332cj2hb937xasg6riziv7yczk1"))

(define rust-io-kit-sys-0.5.0
  ;; TODO REVIEW: Check bundled sources.
  (crate-source "io-kit-sys" "0.5.0"
                "09hw7gy97j0q2qcqf56vhyaa9x2ds509zippvfbnbfwzs14a1lq6"))

(define rust-ioctl-sys-0.8.0
  ;; TODO REVIEW: Check bundled sources.
  (crate-source "ioctl-sys" "0.8.0"
                "0g0kjq308kdm81wq3f1p6q1v2x5sd2v31iwqzzsjch2354x1zlcb"))

(define rust-ipnet-2.11.0
  (crate-source "ipnet" "2.11.0"
                "0c5i9sfi2asai28m8xp48k5gvwkqrg5ffpi767py6mzsrswv17s6"))

(define rust-iri-string-0.7.9
  (crate-source "iri-string" "0.7.9"
                "15s3s6k99ci52d7qdplhllpa6xyvdyiys645n6z6fsw93nfpp1jg"))

(define rust-is-terminal-polyfill-1.70.2
  (crate-source "is_terminal_polyfill" "1.70.2"
                "15anlc47sbz0jfs9q8fhwf0h3vs2w4imc030shdnq54sny5i7jx6"))

(define rust-itertools-0.9.0
  (crate-source "itertools" "0.9.0"
                "0jyml7ygr7kijkcjdl3fk5f34y5h5jsavclim7l13zjiavw1hkr8"))

(define rust-itertools-0.13.0
  (crate-source "itertools" "0.13.0"
                "11hiy3qzl643zcigknclh446qb9zlg4dpdzfkjaa9q9fqpgyfgj1"))

(define rust-itertools-0.14.0
  (crate-source "itertools" "0.14.0"
                "118j6l1vs2mx65dqhwyssbrxpawa90886m3mzafdvyip41w2q69b"))

(define rust-itertools-0.15.0
  (crate-source "itertools" "0.15.0"
                "1p412hriqm4kxn7x1539vz2p5c5s1v2m36m4kis2ai4dyn9syjwb"))

(define rust-itm-0.9.0-rc.1
  (crate-source "itm" "0.9.0-rc.1"
                "04abrp84620daxcihl0s79cmr6vrqzbaqvyc2xqaqf5j921y02fz"))

(define rust-itoa-1.0.16
  (crate-source "itoa" "1.0.16"
                "040hqvfkxl7mpjs54y495ch2qkxx26kbfxyydmi42k7vk8rvbrby"))

(define rust-jep106-0.3.0
  (crate-source "jep106" "0.3.0"
                "1lf61vzvc9lwai374hzaj364jiwinsa6di2cznambzci5k4m84sa"))

(define rust-jiff-0.2.23
  (crate-source "jiff" "0.2.23"
                "0nc37n7jvgrzxdkcgc2hsfdf70lfagigjalh4igjrm5njvf4cd8s"))

(define rust-jiff-static-0.2.23
  (crate-source "jiff-static" "0.2.23"
                "192ss3cnixvg79cpa76clwkhn4mmz10vnwsbf7yjw8i484s8p31a"))

(define rust-jni-0.22.4
  (crate-source "jni" "0.22.4"
                "161lza8gz071h22pgyqyx4n91ixd691z2dbb1pq2g97k5i49mzay"))

(define rust-jni-macros-0.22.4
  (crate-source "jni-macros" "0.22.4"
                "18v02mcn5c7mb2yw6r930xg6ynsn7hwkxv8z2kdhn3qprjn0j0d0"))

(define rust-jni-sys-0.4.1
  ;; TODO REVIEW: Check bundled sources.
  (crate-source "jni-sys" "0.4.1"
                "1wlahx6f2zhczdjqyn8mk7kshb8x5vsd927sn3lvw41rrf47ldy6"))

(define rust-jni-sys-macros-0.4.1
  (crate-source "jni-sys-macros" "0.4.1"
                "0r32gbabrak15a7p487765b5wc0jcna2yv88mk6m1zjqyi1bkh1q"))

(define rust-jobserver-0.1.34
  (crate-source "jobserver" "0.1.34"
                "0cwx0fllqzdycqn4d6nb277qx5qwnmjdxdl0lxkkwssx77j3vyws"))

(define rust-js-sys-0.3.83
  ;; TODO REVIEW: Check bundled sources.
  (crate-source "js-sys" "0.3.83"
                "1n71vpxrzclly0530lwkcsx6mg73lipam2ak3rr1ypzmqw4kfjj6"))

(define rust-kasuari-0.4.11
  (crate-source "kasuari" "0.4.11"
                "0nqa4gkq9jgznnqs8yxzv200lysiny4m152zgn68abk6a08hrscg"))

(define rust-lazy-static-1.5.0
  (crate-source "lazy_static" "1.5.0"
                "1zk6dqqni0193xg6iijh7i3i44sryglwgvx20spdvwk3r6sbrlmv"))

(define rust-libc-0.2.186
  (crate-source "libc" "0.2.186"
                "0rnyhzjyqq9x56skkllbjzzzwym3r61lq3l4hqj64v71gw0r3av8"))

(define rust-libm-0.2.16
  (crate-source "libm" "0.2.16"
                "10brh0a3qjmbzkr5mf5xqi887nhs5y9layvnki89ykz9xb1wxlmn"))

(define rust-libredox-0.1.11
  (crate-source "libredox" "0.1.11"
                "0l7dm6b069y5skdipxg74z1ffmwz75hfxcb5b3r1rvciqbmgc5fz"))

(define rust-libtest-mimic-0.8.2
  (crate-source "libtest-mimic" "0.8.2"
                "0cvzzpwz5bsadb6578xcddf1brcq8b1xfd7qmw2fbrmdy03bmrhl"))

(define rust-libyaml-rs-0.3.0
  (crate-source "libyaml-rs" "0.3.0"
                "0xy7bp2dkr7i2vms63cigb087k7salh95ya4njvilf9ldzd6s4if"))

(define rust-line-clipping-0.3.5
  (crate-source "line-clipping" "0.3.5"
                "0jlakbyjc5sh4j2lx2glyjar3wqq9mqifkdzbhvhkgyxk17f8kaz"))

(define rust-linkme-0.3.36
  (crate-source "linkme" "0.3.36"
                "1ks1mrhf4nc7vy9scfncsiqkv3vw7sn7jib8rbn8vyvkcga74cp8"))

(define rust-linkme-impl-0.3.36
  (crate-source "linkme-impl" "0.3.36"
                "0js4vz4223vdd1wm6imiwvqjxyy7wpgnwdxlcbz0hz9w80h9xm9j"))

(define rust-linux-raw-sys-0.12.1
  ;; TODO REVIEW: Check bundled sources.
  (crate-source "linux-raw-sys" "0.12.1"
                "0lwasljrqxjjfk9l2j8lyib1babh2qjlnhylqzl01nihw14nk9ij"))

(define rust-litemap-0.8.1
  (crate-source "litemap" "0.8.1"
                "0xsy8pfp9s802rsj1bq2ys2kbk1g36w5dr3gkfip7gphb5x60wv3"))

(define rust-litrs-1.0.0
  (crate-source "litrs" "1.0.0"
                "14p0kzzkavnngvybl88nvfwv031cc2qx4vaxpfwsiifm8grdglqi"))

(define rust-lock-api-0.4.14
  (crate-source "lock_api" "0.4.14"
                "0rg9mhx7vdpajfxvdjmgmlyrn20ligzqvn8ifmaz7dc79gkrjhr2"))

(define rust-log-0.4.33
  (crate-source "log" "0.4.33"
                "1bd9dmk22pxgnf0h0slba6rz99zb0a0b2mdhpk8p92bp26ycbvhc"))

(define rust-loom-0.7.2
  (crate-source "loom" "0.7.2"
                "1jpszf9qxv8ydpsm2h9vcyvxvyxcfkhmmfbylzd4gfbc0k40v7j1"))

(define rust-lru-0.18.0
  (crate-source "lru" "0.18.0"
                "1fagimn8n3ivc3diad3jf323lbx86x1cyffjky31dklgjq2hd1la"))

(define rust-lru-slab-0.1.2
  (crate-source "lru-slab" "0.1.2"
                "0m2139k466qj3bnpk66bwivgcx3z88qkxvlzk70vd65jq373jaqi"))

(define rust-lzma-rust2-0.16.2
  (crate-source "lzma-rust2" "0.16.2"
                "1binbd4v550sgyp1larz3dy1c0rz5lj33m0afb7pkdvgisc1xfs7"))

(define rust-mach2-0.4.3
  (crate-source "mach2" "0.4.3"
                "0i6vcnbq5v51whgyidzhf7cbxqrmj2nkw8z0m2ib02rc60mjhh6n"))

(define rust-mach2-0.5.0
  (crate-source "mach2" "0.5.0"
                "1siskhk6qhhzw40k1gc23zg6irx0bqpi1bmm8ns5bv11ak6ra6va"))

(define rust-maitake-sync-0.2.2
  (crate-source "maitake-sync" "0.2.2"
                "0gyywqbh23xr0wysgi5cr3gz7wnv63pwksrv5ih0nj7xpvcqd3vl"))

(define rust-managed-0.8.0
  (crate-source "managed" "0.8.0"
                "13b1j5gpm55jxk24qrbpc25j0ds47bkk9g83d04kp50ab9r8va0c"))

(define rust-matchers-0.2.0
  (crate-source "matchers" "0.2.0"
                "1sasssspdj2vwcwmbq3ra18d3qniapkimfcbr47zmx6750m5llni"))

(define rust-matchit-0.8.4
  (crate-source "matchit" "0.8.4"
                "1hzl48fwq1cn5dvshfly6vzkzqhfihya65zpj7nz7lfx82mgzqa7"))

(define rust-md-5-0.10.6
  (crate-source "md-5" "0.10.6"
                "1kvq5rnpm4fzwmyv5nmnxygdhhb2369888a06gdc9pxyrzh7x7nq"))

(define rust-md-5-0.11.0
  (crate-source "md-5" "0.11.0"
                "166yqj8b11pawpys7knnn77cr618cby2iywpp0dq4dh3b4gl9dk9"))

(define rust-memchr-2.7.6
  (crate-source "memchr" "2.7.6"
                "0wy29kf6pb4fbhfksjbs05jy2f32r2f3r1ga6qkmpz31k79h0azm"))

(define rust-memmap2-0.9.9
  (crate-source "memmap2" "0.9.9"
                "146lfx0mpib44wvws6hibahm4h2w867bzwsc6zhmi9p0l3j36hbl"))

(define rust-miette-7.6.0
  (crate-source "miette" "7.6.0"
                "1dwjnnpcff4jzpf5ns1m19di2p0n5j31zmjv5dskrih7i3nfz62z"))

(define rust-miette-derive-7.6.0
  (crate-source "miette-derive" "7.6.0"
                "12w13a67n2cc37nzidvv0v0vrvf4rsflzxz6slhbn3cm9rqjjnyv"))

(define rust-mime-0.3.17
  (crate-source "mime" "0.3.17"
                "16hkibgvb9klh0w0jk5crr5xv90l3wlf77ggymzjmvl1818vnxv8"))

(define rust-minimal-lexical-0.2.1
  (crate-source "minimal-lexical" "0.2.1"
                "16ppc5g84aijpri4jzv14rvcnslvlpphbszc7zzp6vfkddf4qdb8"))

(define rust-miniz-oxide-0.8.9
  (crate-source "miniz_oxide" "0.8.9"
                "05k3pdg8bjjzayq3rf0qhpirq9k37pxnasfn4arbs17phqn6m9qz"))

(define rust-mio-1.2.0
  (crate-source "mio" "1.2.0"
                "1hanrh4fwsfkdqdaqfidz48zz1wdix23zwn3r2x78am0garfbdsh"))

(define rust-mutex-traits-1.0.1
  (crate-source "mutex-traits" "1.0.1"
                "0gyyiiksykxy2wny28rl37qk94qy7igjx694crxwya9xcfsz4a9r"))

(define rust-mycelium-bitfield-0.1.5
  (crate-source "mycelium-bitfield" "0.1.5"
                "1k21szpzbi0i6f3laczl2d9ls7qyyzgi3sawbk8wnnjq5igcrq14"))

(define rust-nix-0.26.4
  (crate-source "nix" "0.26.4"
                "06xgl4ybb8pvjrbmc3xggbgk3kbs1j0c4c0nzdfrmpbgrkrym2sr"))

(define rust-nix-0.29.0
  (crate-source "nix" "0.29.0"
                "0ikvn7s9r2lrfdm3mx1h7nbfjvcc6s9vxdzw7j5xfkd2qdnp9qki"))

(define rust-nix-0.30.1
  (crate-source "nix" "0.30.1"
                "1dixahq9hk191g0c2ydc0h1ppxj0xw536y6rl63vlnp06lx3ylkl"))

(define rust-nix-0.31.3
  (crate-source "nix" "0.31.3"
                "0gbwnjfny9rq9hl5bz4ry520n9rnfknna4bg88n66f7zx3yx486g"))

(define rust-no-std-io2-0.8.1
  (crate-source "no_std_io2" "0.8.1"
                "1ikjm1hzncqy8jg5p9z5ixg6nxjxpg7cmdlcimvy9c9mf3768dca"))

(define rust-nom-7.1.3
  (crate-source "nom" "7.1.3"
                "0jha9901wxam390jcf5pfa0qqfrgh8li787jx2ip0yk5b8y9hwyj"))

(define rust-nu-ansi-term-0.50.3
  (crate-source "nu-ansi-term" "0.50.3"
                "1ra088d885lbd21q1bxgpqdlk1zlndblmarn948jz2a40xsbjmvr"))

(define rust-num-bigint-0.4.6
  (crate-source "num-bigint" "0.4.6"
                "1f903zd33i6hkjpsgwhqwi2wffnvkxbn6rv4mkgcjcqi7xr4zr55"))

(define rust-num-conv-0.2.2
  (crate-source "num-conv" "0.2.2"
                "0hg4f9bwmy7cwpxdkm165dmkfc8jhkkayci234jsmi5ssb33j5sj"))

(define rust-num-integer-0.1.46
  (crate-source "num-integer" "0.1.46"
                "13w5g54a9184cqlbsq80rnxw4jj4s0d8wv75jsq5r2lms8gncsbr"))

(define rust-num-traits-0.2.19
  (crate-source "num-traits" "0.2.19"
                "0h984rhdkkqd4ny9cif7y2azl3xdfb7768hb9irhpsch4q3gq787"))

(define rust-num-threads-0.1.7
  (crate-source "num_threads" "0.1.7"
                "1ngajbmhrgyhzrlc4d5ga9ych1vrfcvfsiqz6zv0h2dpr2wrhwsw"))

(define rust-nusb-0.2.5
  (crate-source "nusb" "0.2.5"
                "1sas2lha0v2lacs44zxr7k3vsai6syk008cbcm65ws27dwxmbwds"))

(define rust-object-0.36.7
  (crate-source "object" "0.36.7"
                "11vv97djn9nc5n6w1gc6bd96d2qk2c8cg1kw5km9bsi3v4a8x532"))

(define rust-object-0.39.1
  (crate-source "object" "0.39.1"
                "16vkcaamik55jd9f04g73hvgsm5w636gb4w06x3nafvsih4nqnif"))

(define rust-once-cell-1.21.3
  (crate-source "once_cell" "1.21.3"
                "0b9x77lb9f1j6nqgf5aka4s2qj0nly176bpbrv6f9iakk5ff3xa2"))

(define rust-once-cell-polyfill-1.70.2
  (crate-source "once_cell_polyfill" "1.70.2"
                "1zmla628f0sk3fhjdjqzgxhalr2xrfna958s632z65bjsfv8ljrq"))

(define rust-openssl-probe-0.1.6
  (crate-source "openssl-probe" "0.1.6"
                "0bl52x55laalqb707k009h8kfawliwp992rlsvkzy49n47p2fpnh"))

(define rust-option-ext-0.2.0
  (crate-source "option-ext" "0.2.0"
                "0zbf7cx8ib99frnlanpyikm1bx8qn8x602sw1n7bg6p9x94lyx04"))

(define rust-palette-0.7.6
  (crate-source "palette" "0.7.6"
                "1rmn02mv6cb112504qyg7pyfa83c08hxpk5sw7jc5v659hc73gsc"))

(define rust-palette-derive-0.7.6
  (crate-source "palette_derive" "0.7.6"
                "0c0xhpk1nqyq4jr2m8xnka7w47vqzc7m2vq9ih8wxyjv02phs0zm"))

(define rust-parking-2.2.1
  (crate-source "parking" "2.2.1"
                "1fnfgmzkfpjd69v4j9x737b1k8pnn054bvzcn5dm3pkgq595d3gk"))

(define rust-parking-lot-0.12.5
  (crate-source "parking_lot" "0.12.5"
                "06jsqh9aqmc94j2rlm8gpccilqm6bskbd67zf6ypfc0f4m9p91ck"))

(define rust-parking-lot-core-0.9.12
  (crate-source "parking_lot_core" "0.9.12"
                "1hb4rggy70fwa1w9nb0svbyflzdc69h047482v2z3sx2hmcnh896"))

(define rust-parse-int-0.9.0
  (crate-source "parse_int" "0.9.0"
                "0c8snb1cdnakiwqvh62hk1fzvig6hrzqq28mhxddsa9kd5k44ihw"))

(define rust-paste-1.0.15
  (crate-source "paste" "1.0.15"
                "02pxffpdqkapy292harq6asfjvadgp1s005fip9ljfsn9fvxgh2p"))

(define rust-pear-0.2.9
  (crate-source "pear" "0.2.9"
                "0rxlyizzaqq6lswgyfdxjxd3dyb1jfml9gwfpbx5g1j8rq0amvmx"))

(define rust-pear-codegen-0.2.9
  (crate-source "pear_codegen" "0.2.9"
                "0izijffdd2xs762497mk0xr7xwmyw62dzdqjz12v70n0bnc5pasb"))

(define rust-peg-0.8.5
  (crate-source "peg" "0.8.5"
                "0xr42lbgihlwbyfcmjggqv1s3a38agp4j077cd8yqdhv235cya4r"))

(define rust-peg-macros-0.8.5
  (crate-source "peg-macros" "0.8.5"
                "0w8g53c75hz6iy3khc1ja2qm0idpnygjc0xsa9fmpyh2q82ap632"))

(define rust-peg-runtime-0.8.5
  (crate-source "peg-runtime" "0.8.5"
                "1jkgfy5jkjqwqy7h11nn3bmm1qfyn9kq2wnxnlspp4ldhsdwlb8k"))

(define rust-percent-encoding-2.3.2
  (crate-source "percent-encoding" "2.3.2"
                "083jv1ai930azvawz2khv7w73xh8mnylk7i578cifndjn5y64kwv"))

(define rust-pin-project-1.1.10
  (crate-source "pin-project" "1.1.10"
                "12kadbnfm1f43cyadw9gsbyln1cy7vj764wz5c8wxaiza3filzv7"))

(define rust-pin-project-internal-1.1.10
  (crate-source "pin-project-internal" "1.1.10"
                "0qgqzfl0f4lzaz7yl5llhbg97g68r15kljzihaw9wm64z17qx4bf"))

(define rust-pin-project-lite-0.2.16
  (crate-source "pin-project-lite" "0.2.16"
                "16wzc7z7dfkf9bmjin22f5282783f6mdksnr0nv0j5ym5f9gyg1v"))

(define rust-pin-utils-0.1.0
  (crate-source "pin-utils" "0.1.0"
                "117ir7vslsl2z1a7qzhws4pd01cg2d3338c47swjyvqv2n60v1wb"))

(define rust-pkg-config-0.3.32
  (crate-source "pkg-config" "0.3.32"
                "0k4h3gnzs94sjb2ix6jyksacs52cf1fanpwsmlhjnwrdnp8dppby"))

(define rust-plain-0.2.3
  (crate-source "plain" "0.2.3"
                "19n1xbxb4wa7w891268bzf6cbwq4qvdb86bik1z129qb0xnnnndl"))

(define rust-polling-3.11.0
  (crate-source "polling" "3.11.0"
                "0622qfbxi3gb0ly2c99n3xawp878fkrd1sl83hjdhisx11cly3jx"))

(define rust-portable-atomic-1.12.0
  (crate-source "portable-atomic" "1.12.0"
                "1p9rrnq6fdk8byqf1q7x5jbzqwx9yaj99zg8qabmgrgimv2717pm"))

(define rust-portable-atomic-util-0.2.4
  (crate-source "portable-atomic-util" "0.2.4"
                "01rmx1li07ixsx3sqg2bxqrkzk7b5n8pibwwf2589ms0s3cg18nq"))

(define rust-postcard-1.1.3
  (crate-source "postcard" "1.1.3"
                "094srff139n7m8g5ssq36ag6s29ikf7fgpz660x2hkj5vnsw6r37"))

(define rust-postcard-derive-0.2.2
  (crate-source "postcard-derive" "0.2.2"
                "1fz2dw506sbsvsfnm39d183diz17yx3bm0f8kkncx5x11782n8z0"))

(define rust-postcard-rpc-0.12.1
  (crate-source "postcard-rpc" "0.12.1"
                "0b42a99msp2bn77ndbbf2srj51qwddi0fzzvjdc8zwyqig6gkc6i"))

(define rust-postcard-schema-0.2.5
  (crate-source "postcard-schema" "0.2.5"
                "1zr1g9dj2y1jizza2pik9k6vbyd7digjv8vxlnh328pli5nncxcl"))

(define rust-potential-utf-0.1.4
  (crate-source "potential_utf" "0.1.4"
                "0xxg0pkfpq299wvwln409z4fk80rbv55phh3f1jhjajy5x1ljfdp"))

(define rust-powerfmt-0.2.0
  (crate-source "powerfmt" "0.2.0"
                "14ckj2xdpkhv3h6l5sdmb9f1d57z8hbfpdldjc2vl5givq2y77j3"))

(define rust-ppv-lite86-0.2.21
  (crate-source "ppv-lite86" "0.2.21"
                "1abxx6qz5qnd43br1dd9b2savpihzjza8gb4fbzdql1gxp2f7sl5"))

(define rust-pretty-assertions-1.4.1
  (crate-source "pretty_assertions" "1.4.1"
                "0v8iq35ca4rw3rza5is3wjxwsf88303ivys07anc5yviybi31q9s"))

(define rust-proc-macro-crate-3.4.0
  (crate-source "proc-macro-crate" "3.4.0"
                "10v9qi51n4phn1lrj5r94kjq7yhci9jrkqnn6wpan05yjsgb3711"))

(define rust-proc-macro2-1.0.106
  (crate-source "proc-macro2" "1.0.106"
                "0d09nczyaj67x4ihqr5p7gxbkz38gxhk4asc0k8q23g9n85hzl4g"))

(define rust-proc-macro2-diagnostics-0.10.1
  (crate-source "proc-macro2-diagnostics" "0.10.1"
                "1j48ipc80pykvhx6yhndfa774s58ax1h6sm6mlhf09ls76f6l1mg"))

(define rust-quinn-0.11.9
  (crate-source "quinn" "0.11.9"
                "086gzj666dr3slmlynkvxlndy28hahgl361d6bf93hk3i6ahmqmr"))

(define rust-quinn-proto-0.11.14
  (crate-source "quinn-proto" "0.11.14"
                "1660jkxhzi1pnywzs13ifczwrlv6ds9qds111vsnxjciqpz44js3"))

(define rust-quinn-udp-0.5.14
  (crate-source "quinn-udp" "0.5.14"
                "1gacawr17a2zkyri0r3m0lc9spzmxbq1by3ilyb8v2mdvjhcdpmd"))

(define rust-quote-1.0.46
  (crate-source "quote" "1.0.46"
                "0s034glrlav8nzqy2yskqzv52ncy82k126sm2jk5j1vs1iylbg6z"))

(define rust-r-efi-5.3.0
  (crate-source "r-efi" "5.3.0"
                "03sbfm3g7myvzyylff6qaxk4z6fy76yv860yy66jiswc2m6b7kb9"))

(define rust-r-efi-6.0.0
  (crate-source "r-efi" "6.0.0"
                "1gyrl2k5fyzj9k7kchg2n296z5881lg7070msabid09asp3wkp7q"))

(define rust-radium-0.7.0
  (crate-source "radium" "0.7.0"
                "02cxfi3ky3c4yhyqx9axqwhyaca804ws46nn4gc1imbk94nzycyw"))

(define rust-rand-0.9.4
  (crate-source "rand" "0.9.4"
                "1sknbxgs6nfg0nxdd7689lwbyr2i4vaswchrv4b34z8vpc3azia4"))

(define rust-rand-0.10.2
  (crate-source "rand" "0.10.2"
                "105yqkdzqbgggd3r1yjm9jg0zvibfdsmxylvxxkmblwc0lxgmxf7"))

(define rust-rand-chacha-0.9.0
  (crate-source "rand_chacha" "0.9.0"
                "1jr5ygix7r60pz0s1cv3ms1f6pd1i9pcdmnxzzhjc3zn3mgjn0nk"))

(define rust-rand-core-0.9.3
  (crate-source "rand_core" "0.9.3"
                "0f3xhf16yks5ic6kmgxcpv1ngdhp48mmfy4ag82i1wnwh8ws3ncr"))

(define rust-rand-core-0.10.1
  (crate-source "rand_core" "0.10.1"
                "0s9wiacxrr100icl7i41308gcj85nlcclrc5jx1jd6p10dhigf33"))

(define rust-ratatui-0.30.2
  (crate-source "ratatui" "0.30.2"
                "0zfmk50bl3ahjjq0z55h5rmx5njrvks20p80lb9cl6sy5h5blx1j"))

(define rust-ratatui-core-0.1.2
  (crate-source "ratatui-core" "0.1.2"
                "1727mqrvy80hmg5nbf0dwh68rrlnmsi76mqzkn08mqn86g27bcfb"))

(define rust-ratatui-crossterm-0.1.2
  (crate-source "ratatui-crossterm" "0.1.2"
                "1w59rh1xdvd133yxnqskxcjnf9lp2j3b8h6y4cy21a76n2iq8xan"))

(define rust-ratatui-widgets-0.3.2
  (crate-source "ratatui-widgets" "0.3.2"
                "1l87cjanipc1bzwza1mywfn23wbzfrh3pnbpc8vwlc4irjdx3qv6"))

(define rust-redox-syscall-0.5.18
  (crate-source "redox_syscall" "0.5.18"
                "0b9n38zsxylql36vybw18if68yc9jczxmbyzdwyhb9sifmag4azd"))

(define rust-redox-users-0.5.2
  (crate-source "redox_users" "0.5.2"
                "1b17q7gf7w8b1vvl53bxna24xl983yn7bd00gfbii74bcg30irm4"))

(define rust-regex-1.13.1
  (crate-source "regex" "1.13.1"
                "1391a0a4100ik8cp7l577p3ip3haqq03rd9c5vdr7vcfdixj687h"))

(define rust-regex-automata-0.4.16
  (crate-source "regex-automata" "0.4.16"
                "1b8ihxq99g3hr8mr37bvhib4bfn8rlmpmp0wjg2q1j50plvdpkwg"))

(define rust-regex-syntax-0.8.11
  (crate-source "regex-syntax" "0.8.11"
                "1m25h5q2wp976fb9gc3dsc9l99svcvd5cri8lncb51c46ydgzxnn"))

(define rust-reqwest-0.12.28
  (crate-source "reqwest" "0.12.28"
                "0iqidijghgqbzl3bjg5hb4zmigwa4r612bgi0yiq0c90b6jkrpgd"))

(define rust-reqwest-0.13.4
  (crate-source "reqwest" "0.13.4"
                "1hy1plns9krbh3h1dy2sdjygsfkdcnxm6pbxdi0ya9b5vq8mi711"))

(define rust-ring-0.17.14
  (crate-source "ring" "0.17.14"
                "1dw32gv19ccq4hsx3ribhpdzri1vnrlcfqb2vj41xn4l49n9ws54"))

(define rust-rmp-0.8.14
  (crate-source "rmp" "0.8.14"
                "1i1l6dhv7vws5vp0ikakj44fk597xi59g3j6ng1q55x3dz0xg3i2"))

(define rust-rmp-serde-1.3.1
  (crate-source "rmp-serde" "1.3.1"
                "0md1cx5w0hwc40nb55z3c4j26b4npkmp06k8s5vvbycfikp1py3j"))

(define rust-roxmltree-0.20.0
  (crate-source "roxmltree" "0.20.0"
                "15vw91ps91wkmmgy62khf9zb63bdinvm80957dascbsw7dwvc83c"))

(define rust-rustc-demangle-0.1.26
  (crate-source "rustc-demangle" "0.1.26"
                "1kja3nb0yhlm4j2p1hl8d7sjmn2g9fa1s4pj0qma5kj2lcndkxsn"))

(define rust-rustc-hash-2.1.1
  (crate-source "rustc-hash" "2.1.1"
                "03gz5lvd9ghcwsal022cgkq67dmimcgdjghfb5yb5d352ga06xrm"))

(define rust-rustc-version-0.4.1
  (crate-source "rustc_version" "0.4.1"
                "14lvdsmr5si5qbqzrajgb6vfn69k0sfygrvfvr2mps26xwi3mjyg"))

(define rust-rustix-1.1.4
  (crate-source "rustix" "1.1.4"
                "14511f9yjqh0ix07xjrjpllah3325774gfwi9zpq72sip5jlbzmn"))

(define rust-rustls-0.23.42
  (crate-source "rustls" "0.23.42"
                "0f619dq1izpl40glcqgfjbqzpmwg8g5iffjx4429sh4v06mzqm1w"))

(define rust-rustls-native-certs-0.8.2
  (crate-source "rustls-native-certs" "0.8.2"
                "08vr6gyz78c4zmbi8r307pybyrs7hf81wl5s35hm7h5hxcbxk04r"))

(define rust-rustls-pki-types-1.13.2
  (crate-source "rustls-pki-types" "1.13.2"
                "10hjgkw4y5bjkm08j5dskcwpl9qajayshdk7p28l5ji856mz5ri1"))

(define rust-rustls-platform-verifier-0.7.0
  (crate-source "rustls-platform-verifier" "0.7.0"
                "181v4d0vl53vdh2wq56vghal1zyhdgqvy4xa8r45zwz4di9y5l96"))

(define rust-rustls-platform-verifier-android-0.1.1
  (crate-source "rustls-platform-verifier-android" "0.1.1"
                "13vq6sxsgz9547xm2zbdxiw8x7ad1g8n8ax6xvxsjqszk7q6awgq"))

(define rust-rustls-webpki-0.103.13
  (crate-source "rustls-webpki" "0.103.13"
                "0vkm7z9pnxz5qz66p2kmyy2pwx0g4jnsbqk5xzfhs4czcjl2ki31"))

(define rust-rustversion-1.0.22
  (crate-source "rustversion" "1.0.22"
                "0vfl70jhv72scd9rfqgr2n11m5i9l1acnk684m2w83w0zbqdx75k"))

(define rust-rustyline-async-0.4.9
  (crate-source "rustyline-async" "0.4.9"
                "18lkklll3mkplnrjmpv86a9xns5c1n3sw2x519bj7bk42x0m0r5p"))

(define rust-ruzstd-0.8.2
  (crate-source "ruzstd" "0.8.2"
                "009zwq5h4a8nfjwc0kbb0gn69dfr1j8j0csxfw58gj1mw72hrzz5"))

(define rust-ryu-1.0.21
  (crate-source "ryu" "1.0.21"
                "1sja0gi4s0h3yjrx7hky72vivhzx73p5dllsiwg844mzfwl9n132"))

(define rust-same-file-1.0.6
  (crate-source "same-file" "1.0.6"
                "00h5j1w87dmhnvbv9l8bic3y7xxsnjmssvifw2ayvgx9mb1ivz4k"))

(define rust-sanitize-filename-0.6.0
  (crate-source "sanitize-filename" "0.6.0"
                "0kd37m2nd364vj09f330y853fmnw2yyy7hsmnxxnlwzbki7lz65w"))

(define rust-schannel-0.1.28
  (crate-source "schannel" "0.1.28"
                "1qb6s5gyxfz2inz753a4z3mc1d266mwvz0c5w7ppd3h44swq27c9"))

(define rust-schemafy-0.6.0
  (crate-source "schemafy" "0.6.0"
                "06cahdgngimkygfgnjwfrnhrkxpyhfz7f1k3ngy74ng8cimc29cp"))

(define rust-schemafy-core-0.6.0
  (crate-source "schemafy_core" "0.6.0"
                "096ziymx6vi3spw1sj7h7sc76r5mp03jfhhd7hpzjq7yvkfjkv1b"))

(define rust-schemafy-lib-0.6.0
  (crate-source "schemafy_lib" "0.6.0"
                "0pvg39djbbfyy1ijxingz4gb2j4fz3jlw7zx5dz9nsi4vzqqfgdg"))

(define rust-scoped-tls-1.0.1
  (crate-source "scoped-tls" "1.0.1"
                "15524h04mafihcvfpgxd8f4bgc3k95aclz8grjkg9a0rxcvn9kz1"))

(define rust-scopeguard-1.2.0
  (crate-source "scopeguard" "1.2.0"
                "0jcz9sd47zlsgcnm1hdw0664krxwb5gczlif4qngj2aif8vky54l"))

(define rust-scroll-0.13.0
  (crate-source "scroll" "0.13.0"
                "1pbs3vxhrxcvj9hbjw4hiijbqlz0lkfxc9351mv34hcb4ka7q9f1"))

(define rust-scroll-derive-0.13.1
  (crate-source "scroll_derive" "0.13.1"
                "0zd6xq7ffz8nbyjyl603dq16h5d8v95ljl89aw86daqk4gkfyxpd"))

(define rust-security-framework-3.5.1
  (crate-source "security-framework" "3.5.1"
                "1vz6pf5qjgx8s0hg805hq6qbcqnll6fs63irvrpgcc7qx91p6adk"))

(define rust-security-framework-sys-2.15.0
  ;; TODO REVIEW: Check bundled sources.
  (crate-source "security-framework-sys" "2.15.0"
                "1h6mijxnfrwvl1y4dzwn3m877j6dqp9qn3g37i954j5czazhq7yc"))

(define rust-semver-1.0.28
  (crate-source "semver" "1.0.28"
                "1kaimrpy876bcgi8bfj0qqfxk77zm9iz2zhn1hp9hj685z854y4a"))

(define rust-serde-1.0.228
  (crate-source "serde" "1.0.228"
                "17mf4hhjxv5m90g42wmlbc61hdhlm6j9hwfkpcnd72rpgzm993ls"))

(define rust-serde-core-1.0.228
  (crate-source "serde_core" "1.0.228"
                "1bb7id2xwx8izq50098s5j2sqrrvk31jbbrjqygyan6ask3qbls1"))

(define rust-serde-derive-1.0.228
  (crate-source "serde_derive" "1.0.228"
                "0y8xm7fvmr2kjcd029g9fijpndh8csv5m20g4bd76w8qschg4h6m"))

(define rust-serde-json-1.0.150
  (crate-source "serde_json" "1.0.150"
                "1ffgfhy9kndjnrz8lmy95pr758p2zk8dxv6yi99x0vkkni24w0g8"))

(define rust-serde-path-to-error-0.1.20
  (crate-source "serde_path_to_error" "0.1.20"
                "0mxls44p2ycmnxh03zpnlxxygq42w61ws7ir7r0ba6rp5s1gza8h"))

(define rust-serde-plain-1.0.2
  (crate-source "serde_plain" "1.0.2"
                "0l4d4nbw00pz6n43icrc605bhgynfmlyq39sn8i10qasnrnzrqcw"))

(define rust-serde-repr-0.1.20
  (crate-source "serde_repr" "0.1.20"
                "1755gss3f6lwvv23pk7fhnjdkjw7609rcgjlr8vjg6791blf6php"))

(define rust-serde-spanned-0.6.9
  (crate-source "serde_spanned" "0.6.9"
                "18vmxq6qfrm110caszxrzibjhy2s54n1g5w1bshxq9kjmz7y0hdz"))

(define rust-serde-spanned-1.1.1
  (crate-source "serde_spanned" "1.1.1"
                "09jzk7i6wihn3d8i3wi4j4n98ghi93c3b8m8k64nxq0ijn3vaqk6"))

(define rust-serde-urlencoded-0.7.1
  (crate-source "serde_urlencoded" "0.7.1"
                "1zgklbdaysj3230xivihs30qi5vkhigg323a9m62k8jwf4a1qjfk"))

(define rust-serde-with-3.21.0
  (crate-source "serde_with" "3.21.0"
                "134ydsww9awaga8yvcqj7rn8gpcx75z6sa3waywvirqhfd6cb9bn"))

(define rust-serde-yaml-0.9.34+deprecated
  (crate-source "serde_yaml" "0.9.34+deprecated"
                "0isba1fjyg3l6rxk156k600ilzr8fp7crv82rhal0rxz5qd1m2va"))

(define rust-serialport-4.9.0
  (crate-source "serialport" "4.9.0"
                "1wqxcs7p5xk994qy4dx87a9hvy1pz0pkn9j22r7njwviz4b13nd4"))

(define rust-sha1-0.10.6
  (crate-source "sha1" "0.10.6"
                "1fnnxlfg08xhkmwf2ahv634as30l1i3xhlhkvxflmasi5nd85gz3"))

(define rust-sha1-0.11.0
  (crate-source "sha1" "0.11.0"
                "05025pf8d8zr2qq5xyh5m3wqls1fn7813gz1mfs7551mk724rk5a"))

(define rust-sha2-0.10.9
  (crate-source "sha2" "0.10.9"
                "10xjj843v31ghsksd9sl9y12qfc48157j1xpb8v1ml39jy0psl57"))

(define rust-sha2-0.11.0
  (crate-source "sha2" "0.11.0"
                "1x15x22c5yf54ac0np5bfqnq5x0hdw4wqzpi48zwn94ma0bsfss4"))

(define rust-sharded-slab-0.1.7
  (crate-source "sharded-slab" "0.1.7"
                "1xipjr4nqsgw34k7a2cgj9zaasl2ds6jwn89886kww93d32a637l"))

(define rust-shlex-1.3.0
  (crate-source "shlex" "1.3.0"
                "0r1y6bv26c1scpxvhg2cabimrmwgbp4p3wy6syj9n0c4s3q2znhg"))

(define rust-signal-hook-0.3.18
  (crate-source "signal-hook" "0.3.18"
                "1qnnbq4g2vixfmlv28i1whkr0hikrf1bsc4xjy2aasj2yina30fq"))

(define rust-signal-hook-mio-0.2.5
  (crate-source "signal-hook-mio" "0.2.5"
                "1k20rr76ngvmzr6kskkl7dv8iyb84cbydpjbjk3mpcj0lykijnmp"))

(define rust-signal-hook-registry-1.4.7
  (crate-source "signal-hook-registry" "1.4.7"
                "1bgdimrfqcldbplryknv87gywcdj9v29l3nwqbybs5p6p2ca0r3n"))

(define rust-simd-adler32-0.3.8
  (crate-source "simd-adler32" "0.3.8"
                "18lx2gdgislabbvlgw5q3j5ssrr77v8kmkrxaanp3liimp2sc873"))

(define rust-simd-cesu8-1.1.1
  (crate-source "simd_cesu8" "1.1.1"
                "0crcbgvyycmazji2vqj9vxn2czdyl3gxmicp4xqdzkc7pdbh3ycl"))

(define rust-simdutf8-0.1.5
  (crate-source "simdutf8" "0.1.5"
                "0vmpf7xaa0dnaikib5jlx6y4dxd3hxqz6l830qb079g7wcsgxag3"))

(define rust-similar-2.7.0
  (crate-source "similar" "2.7.0"
                "1aidids7ymfr96s70232s6962v5g9l4zwhkvcjp4c5hlb6b5vfxv"))

(define rust-slab-0.4.11
  (crate-source "slab" "0.4.11"
                "12bm4s88rblq02jjbi1dw31984w61y2ldn13ifk5gsqgy97f8aks"))

(define rust-smallvec-1.15.1
  (crate-source "smallvec" "1.15.1"
                "00xxdxxpgyq5vjnpljvkmy99xij5rxgh913ii1v16kzynnivgcb7"))

(define rust-socket2-0.6.3
  (crate-source "socket2" "0.6.3"
                "0gkjjcyn69hqhhlh5kl8byk5m0d7hyrp2aqwzbs3d33q208nwxis"))

(define rust-spidev-0.7.1
  (crate-source "spidev" "0.7.1"
                "15vkqa6rlh48pdb8smhv2hrd42wvfa6xynyi09lj6rbqh4hi0qag"))

(define rust-spin-0.9.8
  (crate-source "spin" "0.9.8"
                "0rvam5r0p3a6qhc18scqpvpgb3ckzyqxpgdfyjnghh8ja7byi039"))

(define rust-ssmarshal-1.0.0
  (crate-source "ssmarshal" "1.0.0"
                "0l5qvcb5knjznr8yaq8dycmhrvcw16wg396z6z9jw698n4isvrpk"))

(define rust-stable-deref-trait-1.2.1
  (crate-source "stable_deref_trait" "1.2.1"
                "15h5h73ppqyhdhx6ywxfj88azmrpml9gl6zp3pwy2malqa6vxqkc"))

(define rust-static-assertions-1.1.0
  (crate-source "static_assertions" "1.1.0"
                "0gsl6xmw10gvn3zs1rv99laj5ig7ylffnh71f9l34js4nr4r7sx2"))

(define rust-strsim-0.11.1
  (crate-source "strsim" "0.11.1"
                "0kzvqlw8hxqb7y598w1s0hxlnmi84sg5vsipp3yg5na5d1rvba3x"))

(define rust-strum-0.27.2
  (crate-source "strum" "0.27.2"
                "1ksb9jssw4bg9kmv9nlgp2jqa4vnsa3y4q9zkppvl952q7vdc8xg"))

(define rust-strum-0.28.0
  (crate-source "strum" "0.28.0"
                "1ggr0if083c1mz9w33hkdjsp0iqk2fz9n49bvb73knwihydxwa4n"))

(define rust-strum-macros-0.27.2
  (crate-source "strum_macros" "0.27.2"
                "19xwikxma0yi70fxkcy1yxcv0ica8gf3jnh5gj936jza8lwcx5bn"))

(define rust-strum-macros-0.28.0
  (crate-source "strum_macros" "0.28.0"
                "0r7n6v5b3x85m52isyc8wq78irmr22g0hmj1xn3pbq8f4yhfx1db"))

(define rust-subtle-2.6.1
  (crate-source "subtle" "2.6.1"
                "14ijxaymghbl1p0wql9cib5zlwiina7kall6w7g89csprkgbvhhk"))

(define rust-svd-parser-0.14.9
  (crate-source "svd-parser" "0.14.9"
                "048q40fx818fxw3zy470ka1lwsvdpy5qf3mjsfkn7qyy8rzf27x4"))

(define rust-svd-rs-0.14.12
  (crate-source "svd-rs" "0.14.12"
                "0n3lfymlvsc6kj4m8s0jld872bjsq5ymhrb9ywzn429gx3i8xf69"))

(define rust-svg-0.18.0
  (crate-source "svg" "0.18.0"
                "18y4ycygzbindx1kqdq8wgm8sm4i3i8g4jwbxrmlzh33s6fdmbwl"))

(define rust-symlink-0.1.0
  (crate-source "symlink" "0.1.0"
                "02h1i0b81mxb4vns4xrvrfibpcvs7jqqav8p3yilwik8cv73r5x7"))

(define rust-syn-1.0.109
  (crate-source "syn" "1.0.109"
                "0ds2if4600bd59wsv7jjgfkayfzy3hnazs394kz6zdkmna8l3dkj"))

(define rust-syn-2.0.119
  (crate-source "syn" "2.0.119"
                "15vjy620l91a3q4n4f4gzhnflmdr6pnm38v2m6cpk86i8av32a47"))

(define rust-sync-wrapper-1.0.2
  (crate-source "sync_wrapper" "1.0.2"
                "0qvjyasd6w18mjg5xlaq5jgy84jsjfsvmnn12c13gypxbv75dwhb"))

(define rust-synstructure-0.13.2
  (crate-source "synstructure" "0.13.2"
                "1lh9lx3r3jb18f8sbj29am5hm9jymvbwh6jb1izsnnxgvgrp12kj"))

(define rust-tap-1.0.1
  (crate-source "tap" "1.0.1"
                "0sc3gl4nldqpvyhqi3bbd0l9k7fngrcl4zs47n314nqqk4bpx4sm"))

(define rust-target-triple-1.0.0
  (crate-source "target-triple" "1.0.0"
                "0yvp9fn2854wzj8rnyi3xr5r8wc7rfag8b733rvs935pvy7g67jr"))

(define rust-tempfile-3.27.0
  (crate-source "tempfile" "3.27.0"
                "1gblhnyfjsbg9wjg194n89wrzah7jy3yzgnyzhp56f3v9jd7wj9j"))

(define rust-termcolor-1.4.1
  (crate-source "termcolor" "1.4.1"
                "0mappjh3fj3p2nmrg4y7qv94rchwi9mzmgmfflr8p2awdj7lyy86"))

(define rust-termtree-1.0.0
  (crate-source "termtree" "1.0.0"
                "1nffshav2518pq4vx1gx0nr6gmh20sqk0l8n0p6p5y7pww7k7lfl"))

(define rust-test-case-3.3.1
  (crate-source "test-case" "3.3.1"
                "1a380yzm6787737cw7s09jqmkn9035hghahradl2ikdg2gfm09gb"))

(define rust-test-case-core-3.3.1
  (crate-source "test-case-core" "3.3.1"
                "0krqi0gbi1yyycigyjlak63r8h1n0vms7mg3kckqwlfd87c7zjxd"))

(define rust-test-case-macros-3.3.1
  (crate-source "test-case-macros" "3.3.1"
                "1yvgky3qax73bic6m368q04xc955p4a91mddd6b5fk7d04mfg2aw"))

(define rust-test-log-0.2.21
  (crate-source "test-log" "0.2.21"
                "1wa0xspccq5qdgf1831zj8nk2fn5dxpsn0w3ns4mqar4hj1j374v"))

(define rust-test-log-core-0.2.21
  (crate-source "test-log-core" "0.2.21"
                "0yzj2fgz58lylslmi8r1kyr5nfhbg76v7pd8yrcjwf2d1sqghvn2"))

(define rust-test-log-macros-0.2.21
  (crate-source "test-log-macros" "0.2.21"
                "13dcgnvrgcjwvq7jmp1y9cmshk4y0zmwwsy5hakflwdvvj5d6jll"))

(define rust-textwrap-0.16.2
  (crate-source "textwrap" "0.16.2"
                "0mrhd8q0dnh5hwbwhiv89c6i41yzmhw4clwa592rrp24b9hlfdf1"))

(define rust-thingbuf-0.1.6
  (crate-source "thingbuf" "0.1.6"
                "01d9pix5ljhnsfz2ws0vz7r8x3idpdxpip6shgv72kkvdzpm8av6"))

(define rust-thiserror-1.0.69
  (crate-source "thiserror" "1.0.69"
                "0lizjay08agcr5hs9yfzzj6axs53a2rgx070a1dsi3jpkcrzbamn"))

(define rust-thiserror-2.0.18
  (crate-source "thiserror" "2.0.18"
                "1i7vcmw9900bvsmay7mww04ahahab7wmr8s925xc083rpjybb222"))

(define rust-thiserror-impl-1.0.69
  (crate-source "thiserror-impl" "1.0.69"
                "1h84fmn2nai41cxbhk6pqf46bxqq1b344v8yz089w1chzi76rvjg"))

(define rust-thiserror-impl-2.0.18
  (crate-source "thiserror-impl" "2.0.18"
                "1mf1vrbbimj1g6dvhdgzjmn6q09yflz2b92zs1j9n3k7cxzyxi7b"))

(define rust-thread-local-1.1.9
  (crate-source "thread_local" "1.1.9"
                "1191jvl8d63agnq06pcnarivf63qzgpws5xa33hgc92gjjj4c0pn"))

(define rust-time-0.3.53
  (crate-source "time" "0.3.53"
                "0l4aans0kv47y53736cjs0pnvdz91iyywrkqbrxk6cmrvknsmpqq"))

(define rust-time-core-0.1.9
  (crate-source "time-core" "0.1.9"
                "028ix0ax7ixp1h1k5zsqwgw85w6y1q32irslma7ci6ddd5kr074y"))

(define rust-time-macros-0.2.31
  (crate-source "time-macros" "0.2.31"
                "0pq8y9bm1zr008dmjs62qdfwsigv2kwkga5sj0d4jvk625qvhcf4"))

(define rust-tinystr-0.8.2
  (crate-source "tinystr" "0.8.2"
                "0sa8z88axdsf088hgw5p4xcyi6g3w3sgbb6qdp81bph9bk2fkls2"))

(define rust-tinyvec-1.10.0
  (crate-source "tinyvec" "1.10.0"
                "1yhk0qdqyiaa4v2j9h8pzax5gxgwpz4da0lcphfil6g6pk1zv9dz"))

(define rust-tinyvec-macros-0.1.1
  (crate-source "tinyvec_macros" "0.1.1"
                "081gag86208sc3y6sdkshgw3vysm5d34p431dzw0bshz66ncng0z"))

(define rust-tokio-1.53.0
  (crate-source "tokio" "1.53.0"
                "1vpzc93iaiaqk90jh54vqji8fawiiksk4cwh8qyns1xy5pavr26r"))

(define rust-tokio-macros-2.7.0
  (crate-source "tokio-macros" "2.7.0"
                "15m4f37mdafs0gg36sh0rskm1i768lb7zmp8bw67kaxr3avnqniq"))

(define rust-tokio-rustls-0.26.4
  (crate-source "tokio-rustls" "0.26.4"
                "0qggwknz9w4bbsv1z158hlnpkm97j3w8v31586jipn99byaala8p"))

(define rust-tokio-tungstenite-0.29.0
  (crate-source "tokio-tungstenite" "0.29.0"
                "0p4i0a9fwhn92y4ybc0z75pc8hn2hjjgnlymminqb1c5h9ga0wlg"))

(define rust-tokio-tungstenite-0.30.0
  (crate-source "tokio-tungstenite" "0.30.0"
                "0wdx24sfglza6fcvz2p04aawv4wa80qq01ksd4va4gsnxnzp780p"))

(define rust-tokio-util-0.7.18
  (crate-source "tokio-util" "0.7.18"
                "1600rd47pylwn7cap1k7s5nvdaa9j7w8kqigzp1qy7mh0p4cxscs"))

(define rust-toml-0.8.23
  (crate-source "toml" "0.8.23"
                "0qnkrq4lm2sdhp3l6cb6f26i8zbnhqb7mhbmksd550wxdfcyn6yw"))

(define rust-toml-1.1.3+spec-1.1.0
  (crate-source "toml" "1.1.3+spec-1.1.0"
                "0g2c3lqf61ss14ak0lzg5r8fvsx8mnclzldfzk28y74lzb6nxjak"))

(define rust-toml-datetime-0.6.11
  (crate-source "toml_datetime" "0.6.11"
                "077ix2hb1dcya49hmi1avalwbixmrs75zgzb3b2i7g2gizwdmk92"))

(define rust-toml-datetime-0.7.5+spec-1.1.0
  (crate-source "toml_datetime" "0.7.5+spec-1.1.0"
                "0iqkgvgsxmszpai53dbip7sf2igic39s4dby29dbqf1h9bnwzqcj"))

(define rust-toml-datetime-1.1.1+spec-1.1.0
  (crate-source "toml_datetime" "1.1.1+spec-1.1.0"
                "1mws2mkkf46l7inn77azhm0vdwxngv9vsbhbl0ah33p2c9gzcr9i"))

(define rust-toml-edit-0.22.27
  (crate-source "toml_edit" "0.22.27"
                "16l15xm40404asih8vyjvnka9g0xs9i4hfb6ry3ph9g419k8rzj1"))

(define rust-toml-edit-0.23.10+spec-1.0.0
  (crate-source "toml_edit" "0.23.10+spec-1.0.0"
                "0saj5c676j8a3sqaj9akkp09wambg8aflji4zblwwa70azvvkj44"))

(define rust-toml-parser-1.1.2+spec-1.1.0
  (crate-source "toml_parser" "1.1.2+spec-1.1.0"
                "09kmzc55a0j21whm290wlf5a8b18a0qc87a1s8sncrckc6wfkax2"))

(define rust-toml-write-0.1.2
  (crate-source "toml_write" "0.1.2"
                "008qlhqlqvljp1gpp9rn5cqs74gwvdgbvs92wnpq8y3jlz4zi6ax"))

(define rust-toml-writer-1.1.2+spec-1.1.0
  (crate-source "toml_writer" "1.1.2+spec-1.1.0"
                "1lk6pqf9mac3v1x6282n6a66qx5b18c8f4a23bsd0nk658x3amkx"))

(define rust-tower-0.5.2
  (crate-source "tower" "0.5.2"
                "1ybmd59nm4abl9bsvy6rx31m4zvzp5rja2slzpn712y9b68ssffh"))

(define rust-tower-http-0.6.8
  (crate-source "tower-http" "0.6.8"
                "1y514jwzbyrmrkbaajpwmss4rg0mak82k16d6588w9ncaffmbrnl"))

(define rust-tower-layer-0.3.3
  (crate-source "tower-layer" "0.3.3"
                "03kq92fdzxin51w8iqix06dcfgydyvx7yr6izjq0p626v9n2l70j"))

(define rust-tower-service-0.3.3
  (crate-source "tower-service" "0.3.3"
                "1hzfkvkci33ra94xjx64vv3pp0sq346w06fpkcdwjcid7zhvdycd"))

(define rust-tracing-0.1.44
  (crate-source "tracing" "0.1.44"
                "006ilqkg1lmfdh3xhg3z762izfwmxcvz0w7m4qx2qajbz9i1drv3"))

(define rust-tracing-appender-0.2.5
  (crate-source "tracing-appender" "0.2.5"
                "0g4a6q5s3wafid5lqw1ljzvh1nhk3a4zmb627fxv96dr7qcqc1h5"))

(define rust-tracing-attributes-0.1.31
  (crate-source "tracing-attributes" "0.1.31"
                "1np8d77shfvz0n7camx2bsf1qw0zg331lra0hxb4cdwnxjjwz43l"))

(define rust-tracing-core-0.1.36
  (crate-source "tracing-core" "0.1.36"
                "16mpbz6p8vd6j7sf925k9k8wzvm9vdfsjbynbmaxxyq6v7wwm5yv"))

(define rust-tracing-log-0.2.0
  (crate-source "tracing-log" "0.2.0"
                "1hs77z026k730ij1a9dhahzrl0s073gfa2hm5p0fbl0b80gmz1gf"))

(define rust-tracing-serde-0.2.0
  (crate-source "tracing-serde" "0.2.0"
                "1wbgzi364vzfswfkvy48a3p0z5xmv98sx342r57sil70ggmiljvh"))

(define rust-tracing-subscriber-0.3.23
  (crate-source "tracing-subscriber" "0.3.23"
                "06fkr0qhggvrs861d7f74pn3i3a10h5jsp4n70jj9ys5b675fzyb"))

(define rust-trait-variant-0.1.2
  (crate-source "trait-variant" "0.1.2"
                "19vpbnbcsxdiznwdw854pd0vya7rm7v7hnl3nh741621603pg5vh"))

(define rust-try-lock-0.2.5
  (crate-source "try-lock" "0.2.5"
                "0jqijrrvm1pyq34zn1jmy2vihd4jcrjlvsh4alkjahhssjnsn8g4"))

(define rust-trybuild-1.0.118
  (crate-source "trybuild" "1.0.118"
                "0y2cc9m5pmw1yhlndz3hzmxa3jczhahxal491jx08rnqcdprqr06"))

(define rust-tungstenite-0.29.0
  (crate-source "tungstenite" "0.29.0"
                "1f7673dhqbfxc0f2ccyiyqhv882nkialnzm5qb3vkbwky8m1a0bc"))

(define rust-tungstenite-0.30.0
  (crate-source "tungstenite" "0.30.0"
                "08lxarf1fbb0zf9y04hf1ss9rb0m8ar2h8dba051375ifiqwg2p4"))

(define rust-twox-hash-2.1.2
  (crate-source "twox-hash" "2.1.2"
                "1721278f1yc5zvkpdb8gsb1x6nlfjdmwm5fk9ff3fismcxmi78wy"))

(define rust-typed-arena-2.0.2
  (crate-source "typed-arena" "2.0.2"
                "0shj0jpmglhgw2f1i4b33ycdzwd1z205pbs1rd5wx7ks2qhaxxka"))

(define rust-typed-path-0.12.3
  (crate-source "typed-path" "0.12.3"
                "03k051dafrnyg3lbm4c85zg0mpfhbn6l9aq4ryq8yyy8h2dzha4f"))

(define rust-typenum-1.19.0
  (crate-source "typenum" "1.19.0"
                "1fw2mpbn2vmqan56j1b3fbpcdg80mz26fm53fs16bq5xcq84hban"))

(define rust-uf2-decode-0.2.0
  (crate-source "uf2-decode" "0.2.0"
                "08q6n1xd9n418sshdngf6a36s35qg5ngjhr0yifs8gvyn8dd8xya"))

(define rust-uncased-0.9.10
  (crate-source "uncased" "0.9.10"
                "15q6r6g4fszr8c2lzg9z9k9g52h8g29h24awda3d72cyw37qzf71"))

(define rust-unescaper-0.1.8
  (crate-source "unescaper" "0.1.8"
                "13hkl55sgny2kq7p1z6f32fsnjz3y949a3izpljvqza8bilfsr20"))

(define rust-unicode-ident-1.0.22
  (crate-source "unicode-ident" "1.0.22"
                "1x8xrz17vqi6qmkkcqr8cyf0an76ig7390j9cnqnk47zyv2gf4lk"))

(define rust-unicode-linebreak-0.1.5
  (crate-source "unicode-linebreak" "0.1.5"
                "07spj2hh3daajg335m4wdav6nfkl0f6c0q72lc37blr97hych29v"))

(define rust-unicode-segmentation-1.12.0
  (crate-source "unicode-segmentation" "1.12.0"
                "14qla2jfx74yyb9ds3d2mpwpa4l4lzb9z57c6d2ba511458z5k7n"))

(define rust-unicode-truncate-2.0.0
  (crate-source "unicode-truncate" "2.0.0"
                "0c33c29m85wb5c0vbvz724f3rinsz0l5zjhh74pp0f7l1y307gwg"))

(define rust-unicode-width-0.1.14
  (crate-source "unicode-width" "0.1.14"
                "1bzn2zv0gp8xxbxbhifw778a7fc93pa6a1kj24jgg9msj07f7mkx"))

(define rust-unicode-width-0.2.0
  (crate-source "unicode-width" "0.2.0"
                "1zd0r5vs52ifxn25rs06gxrgz8cmh4xpra922k0xlmrchib1kj0z"))

(define rust-unit-prefix-0.5.2
  (crate-source "unit-prefix" "0.5.2"
                "18xr6yhdvlxrv51y6js9npa3qhkzc5b1z4skr5kfzn7kkd449rc1"))

(define rust-unsafe-libyaml-0.2.11
  (crate-source "unsafe-libyaml" "0.2.11"
                "0qdq69ffl3v5pzx9kzxbghzn0fzn266i1xn70y88maybz9csqfk7"))

(define rust-untrusted-0.9.0
  (crate-source "untrusted" "0.9.0"
                "1ha7ib98vkc538x0z60gfn0fc5whqdd85mb87dvisdcaifi6vjwf"))

(define rust-unty-0.0.4
  (crate-source "unty" "0.0.4"
                "1blhyv01qiv5sb72sal3xa1l8nzck3answawxkkiw3fd2x1phjbd"))

(define rust-uriparse-0.6.4
  (crate-source "uriparse" "0.6.4"
                "1zsjwc715x4720y4b3dsdras50imvaakqgyl59n3j2fq0kyd0002"))

(define rust-url-2.5.8
  (crate-source "url" "2.5.8"
                "1v8f7nx3hpr1qh76if0a04sj08k86amsq4h8cvpw6wvk76jahrzz"))

(define rust-urlencoding-2.1.3
  (crate-source "urlencoding" "2.1.3"
                "1nj99jp37k47n0hvaz5fvz7z6jd0sb4ppvfy3nphr1zbnyixpy6s"))

(define rust-utf8-iter-1.0.4
  (crate-source "utf8_iter" "1.0.4"
                "1gmna9flnj8dbyd8ba17zigrp9c4c3zclngf5lnb5yvz1ri41hdn"))

(define rust-utf8parse-0.2.2
  (crate-source "utf8parse" "0.2.2"
                "088807qwjq46azicqwbhlmzwrbkz7l4hpw43sdkdyyk524vdxaq6"))

(define rust-uuid-1.24.0
  (crate-source "uuid" "1.24.0"
                "0faj5x0zgri8m3i8dv9qgyhiwqwdyhbl2g351cp3iin4ynk26fdz"))

(define rust-valuable-0.1.1
  (crate-source "valuable" "0.1.1"
                "0r9srp55v7g27s5bg7a2m095fzckrcdca5maih6dy9bay6fflwxs"))

(define rust-version-check-0.9.5
  (crate-source "version_check" "0.9.5"
                "0nhhi4i5x89gm911azqbn7avs9mdacw2i3vcz3cnmz3mv4rqz4hb"))

(define rust-virtue-0.0.18
  (crate-source "virtue" "0.0.18"
                "1cgp79pzzs117kjlc3jnnkixbyaqri12j40mx2an41qhrymv27h5"))

(define rust-walkdir-2.5.0
  (crate-source "walkdir" "2.5.0"
                "0jsy7a710qv8gld5957ybrnc07gavppp963gs32xk4ag8130jy99"))

(define rust-want-0.3.1
  (crate-source "want" "0.3.1"
                "03hbfrnvqqdchb5kgxyavb9jabwza0dmh2vw5kg0dq8rxl57d9xz"))

(define rust-wasi-0.11.1+wasi-snapshot-preview1
  (crate-source "wasi" "0.11.1+wasi-snapshot-preview1"
                "0jx49r7nbkbhyfrfyhz0bm4817yrnxgd3jiwwwfv0zl439jyrwyc"))

(define rust-wasip2-1.0.1+wasi-0.2.4
  (crate-source "wasip2" "1.0.1+wasi-0.2.4"
                "1rsqmpspwy0zja82xx7kbkbg9fv34a4a2if3sbd76dy64a244qh5"))

(define rust-wasm-bindgen-0.2.106
  (crate-source "wasm-bindgen" "0.2.106"
                "1zc0pcyv0w1dhp8r7ybmmfjsf4g18q784h0k7mv2sjm67x1ryx8d"))

(define rust-wasm-bindgen-futures-0.4.56
  (crate-source "wasm-bindgen-futures" "0.4.56"
                "0z6f0zkylpgbfb7dkh7a85dxdwm57q7c2np2bngfxzh4sqi9cvc3"))

(define rust-wasm-bindgen-macro-0.2.106
  (crate-source "wasm-bindgen-macro" "0.2.106"
                "1czfwzhqrkzyyhd3g58mdwb2jjk4q2pl9m1fajyfvfpq70k0vjs8"))

(define rust-wasm-bindgen-macro-support-0.2.106
  (crate-source "wasm-bindgen-macro-support" "0.2.106"
                "0h6ddq6cc6jf9phsdh2a3x8lpjhmkya86ihfz3fdk4jzrpamkyyf"))

(define rust-wasm-bindgen-shared-0.2.106
  (crate-source "wasm-bindgen-shared" "0.2.106"
                "1d0dh3jn77qz67n5zh0s3rvzlbjv926p0blq5bvng2v4gq2kiifb"))

(define rust-wasm-streams-0.4.2
  (crate-source "wasm-streams" "0.4.2"
                "0rddn007hp6k2cm91mm9y33n79b0jxv0c3znzszcvv67hn6ks18m"))

(define rust-web-sys-0.3.83
  ;; TODO REVIEW: Check bundled sources.
  (crate-source "web-sys" "0.3.83"
                "1b1pw450ig62xr0cy1wfjlbahvmi725jl64d150j0hacfy6q4clv"))

(define rust-web-time-1.1.0
  (crate-source "web-time" "1.1.0"
                "1fx05yqx83dhx628wb70fyy10yjfq1jpl20qfqhdkymi13rq0ras"))

(define rust-webpki-root-certs-1.0.7
  (crate-source "webpki-root-certs" "1.0.7"
                "0b59x5mzsilk42w59nif3lfhc24pgzb0v35pi6p01qy37z7424gk"))

(define rust-webpki-roots-0.26.11
  (crate-source "webpki-roots" "0.26.11"
                "1agpayg5zzf7m1a01q30jahlgmn5nwggbabdhq0in008pf5c66sj"))

(define rust-webpki-roots-1.0.4
  (crate-source "webpki-roots" "1.0.4"
                "07jp2zgj3hjb60m1nwrasixdwazmzhh9y4bryy66wz6457q8x1xj"))

(define rust-winapi-0.3.9
  (crate-source "winapi" "0.3.9"
                "06gl025x418lchw1wxj64ycr7gha83m44cjr5sarhynd9xkrm0sw"))

(define rust-winapi-i686-pc-windows-gnu-0.4.0
  (crate-source "winapi-i686-pc-windows-gnu" "0.4.0"
                "1dmpa6mvcvzz16zg6d5vrfy4bxgg541wxrcip7cnshi06v38ffxc"))

(define rust-winapi-util-0.1.11
  (crate-source "winapi-util" "0.1.11"
                "08hdl7mkll7pz8whg869h58c1r9y7in0w0pk8fm24qc77k0b39y2"))

(define rust-winapi-x86-64-pc-windows-gnu-0.4.0
  (crate-source "winapi-x86_64-pc-windows-gnu" "0.4.0"
                "0gqq64czqb64kskjryj8isp62m2sgvx25yyj3kpc2myh85w24bki"))

(define rust-windows-core-0.62.2
  (crate-source "windows-core" "0.62.2"
                "1swxpv1a8qvn3bkxv8cn663238h2jccq35ff3nsj61jdsca3ms5q"))

(define rust-windows-implement-0.60.2
  (crate-source "windows-implement" "0.60.2"
                "1psxhmklzcf3wjs4b8qb42qb6znvc142cb5pa74rsyxm1822wgh5"))

(define rust-windows-interface-0.59.3
  (crate-source "windows-interface" "0.59.3"
                "0n73cwrn4247d0axrk7gjp08p34x1723483jxjxjdfkh4m56qc9z"))

(define rust-windows-link-0.2.1
  (crate-source "windows-link" "0.2.1"
                "1rag186yfr3xx7piv5rg8b6im2dwcf8zldiflvb22xbzwli5507h"))

(define rust-windows-result-0.4.1
  (crate-source "windows-result" "0.4.1"
                "1d9yhmrmmfqh56zlj751s5wfm9a2aa7az9rd7nn5027nxa4zm0bp"))

(define rust-windows-strings-0.5.1
  (crate-source "windows-strings" "0.5.1"
                "14bhng9jqv4fyl7lqjz3az7vzh8pw0w4am49fsqgcz67d67x0dvq"))

(define rust-windows-sys-0.52.0
  ;; TODO REVIEW: Check bundled sources.
  (crate-source "windows-sys" "0.52.0"
                "0gd3v4ji88490zgb6b5mq5zgbvwv7zx1ibn8v3x83rwcdbryaar8"))

(define rust-windows-sys-0.61.2
  ;; TODO REVIEW: Check bundled sources.
  (crate-source "windows-sys" "0.61.2"
                "1z7k3y9b6b5h52kid57lvmvm05362zv1v8w0gc7xyv5xphlp44xf"))

(define rust-windows-targets-0.52.6
  (crate-source "windows-targets" "0.52.6"
                "0wwrx625nwlfp7k93r2rra568gad1mwd888h1jwnl0vfg5r4ywlv"))

(define rust-windows-aarch64-gnullvm-0.52.6
  (crate-source "windows_aarch64_gnullvm" "0.52.6"
                "1lrcq38cr2arvmz19v32qaggvj8bh1640mdm9c2fr877h0hn591j"))

(define rust-windows-aarch64-msvc-0.52.6
  (crate-source "windows_aarch64_msvc" "0.52.6"
                "0sfl0nysnz32yyfh773hpi49b1q700ah6y7sacmjbqjjn5xjmv09"))

(define rust-windows-i686-gnu-0.52.6
  (crate-source "windows_i686_gnu" "0.52.6"
                "02zspglbykh1jh9pi7gn8g1f97jh1rrccni9ivmrfbl0mgamm6wf"))

(define rust-windows-i686-gnullvm-0.52.6
  (crate-source "windows_i686_gnullvm" "0.52.6"
                "0rpdx1537mw6slcpqa0rm3qixmsb79nbhqy5fsm3q2q9ik9m5vhf"))

(define rust-windows-i686-msvc-0.52.6
  (crate-source "windows_i686_msvc" "0.52.6"
                "0rkcqmp4zzmfvrrrx01260q3xkpzi6fzi2x2pgdcdry50ny4h294"))

(define rust-windows-x86-64-gnu-0.52.6
  (crate-source "windows_x86_64_gnu" "0.52.6"
                "0y0sifqcb56a56mvn7xjgs8g43p33mfqkd8wj1yhrgxzma05qyhl"))

(define rust-windows-x86-64-gnullvm-0.52.6
  (crate-source "windows_x86_64_gnullvm" "0.52.6"
                "03gda7zjx1qh8k9nnlgb7m3w3s1xkysg55hkd1wjch8pqhyv5m94"))

(define rust-windows-x86-64-msvc-0.52.6
  (crate-source "windows_x86_64_msvc" "0.52.6"
                "1v7rb5cibyzx8vak29pdrk8nx9hycsjs4w0jgms08qk49jl6v7sq"))

(define rust-winnow-0.7.14
  (crate-source "winnow" "0.7.14"
                "0a88ahjqhyn2ln1yplq2xsigm09kxqkdkkk2c2mfxkbzszln8lss"))

(define rust-winnow-1.0.0
  (crate-source "winnow" "1.0.0"
                "1n67gx8mg2b6r2z54zwbrb6qsfbdsar1lvafsfaajr3jcvj8h3m9"))

(define rust-wit-bindgen-0.46.0
  (crate-source "wit-bindgen" "0.46.0"
                "0ngysw50gp2wrrfxbwgp6dhw1g6sckknsn3wm7l00vaf7n48aypi"))

(define rust-writeable-0.6.2
  (crate-source "writeable" "0.6.2"
                "1fg08y97n6vk7l0rnjggw3xyrii6dcqg54wqaxldrlk98zdy1pcy"))

(define rust-wyz-0.5.1
  (crate-source "wyz" "0.5.1"
                "1vdrfy7i2bznnzjdl9vvrzljvs4s3qm8bnlgqwln6a941gy61wq5"))

(define rust-xshell-0.2.7
  (crate-source "xshell" "0.2.7"
                "0g9pd9bfp0f35rzichic55k7p1mn8mqp607y5rimhiq14g390wly"))

(define rust-xshell-macros-0.2.7
  (crate-source "xshell-macros" "0.2.7"
                "0irm50jxdc92r0kd6yvl5p28jsfzha59brxk7z9w3jcf7z6h1b1j"))

(define rust-yaml-serde-0.10.4
  (crate-source "yaml_serde" "0.10.4"
                "0x9rdrjh50i8s44gl70ikf4m33liz2j22v0sfjradj57lsqw3iq8"))

(define rust-yansi-1.0.1
  (crate-source "yansi" "1.0.1"
                "0jdh55jyv0dpd38ij4qh60zglbw9aa8wafqai6m0wa7xaxk3mrfg"))

(define rust-yoke-0.8.1
  (crate-source "yoke" "0.8.1"
                "0m29dm0bf5iakxgma0bj6dbmc3b8qi9b1vaw9sa76kdqmz3fbmkj"))

(define rust-yoke-derive-0.8.1
  (crate-source "yoke-derive" "0.8.1"
                "0pbyja133jnng4mrhimzdq4a0y26421g734ybgz8wsgbfhl0andn"))

(define rust-zerocopy-0.8.54
  (crate-source "zerocopy" "0.8.54"
                "06cxymy8i9q9a93xdins9ayakx9b1nc2arb7qdfd03ssf05brjxp"))

(define rust-zerocopy-derive-0.8.54
  (crate-source "zerocopy-derive" "0.8.54"
                "1xb292dhgb0d4fs05cdj2s0v3srmk7bajv94sdc7631dnnvigs72"))

(define rust-zerofrom-0.1.6
  (crate-source "zerofrom" "0.1.6"
                "19dyky67zkjichsb7ykhv0aqws3q0jfvzww76l66c19y6gh45k2h"))

(define rust-zerofrom-derive-0.1.6
  (crate-source "zerofrom-derive" "0.1.6"
                "00l5niw7c1b0lf1vhvajpjmcnbdp2vn96jg4nmkhq2db0rp5s7np"))

(define rust-zeroize-1.8.2
  (crate-source "zeroize" "1.8.2"
                "1l48zxgcv34d7kjskr610zqsm6j2b4fcr2vfh9jm9j1jgvk58wdr"))

(define rust-zerotrie-0.2.3
  (crate-source "zerotrie" "0.2.3"
                "0lbqznlqazmrwwzslw0ci7p3pqxykrbfhq29npj0gmb2amxc2n9a"))

(define rust-zerovec-0.11.5
  (crate-source "zerovec" "0.11.5"
                "00m0p47k2g9mkv505hky5xh3r6ps7v8qc0dy4pspg542jj972a3c"))

(define rust-zerovec-derive-0.11.2
  (crate-source "zerovec-derive" "0.11.2"
                "1wsig4h5j7a1scd5hrlnragnazjny9qjc44hancb6p6a76ay7p7a"))

(define rust-zip-8.6.0
  (crate-source "zip" "8.6.0"
                "16w0aiqiymyy6kjri0aykkmh45pbk6a6ck69hxhal0hm72ssc11d"))

(define rust-zlib-rs-0.6.0
  (crate-source "zlib-rs" "0.6.0"
                "0g3ydblvzjn6lfs04q3myxxmvzn1a660whp9nr137g6chbv8m557"))

(define rust-zmij-1.0.2
  (crate-source "zmij" "1.0.2"
                "0795wc0mal0ipxa4gass848bfgscgzhdpz04kwajvin5kn74wjhg"))

(define rust-zopfli-0.8.3
  (crate-source "zopfli" "0.8.3"
                "0jaj5dyh3mks0805h4ldrsh5pwq4i2jc9dc9zwjm91k3gmwxhp7h"))

(define rust-zstd-0.13.3
  (crate-source "zstd" "0.13.3"
                "12n0h4w9l526li7jl972rxpyf012jw3nwmji2qbjghv9ll8y67p9"))

(define rust-zstd-safe-7.2.4
  (crate-source "zstd-safe" "7.2.4"
                "179vxmkzhpz6cq6mfzvgwc99bpgllkr6lwxq7ylh5dmby3aw8jcg"))

(define rust-zstd-sys-2.0.16+zstd.1.5.7
  ;; TODO REVIEW: Check bundled sources.
  (crate-source "zstd-sys" "2.0.16+zstd.1.5.7"
                "0j1pd2iaqpvaxlgqmmijj68wma7xwdv9grrr63j873yw5ay9xqci"))


(define-cargo-inputs lookup-cargo-inputs
  (probe-rs-tools =>
   (list
    rust-inflector-0.11.4
    rust-addr2line-0.27.0
    rust-adler2-2.0.1
    rust-aho-corasick-1.1.4
    rust-allocator-api2-0.2.21
    rust-alterable-logger-1.0.1
    rust-android-system-properties-0.1.5
    rust-ansi-parser-0.9.1
    rust-ansi-width-0.1.0
    rust-anstream-1.0.0
    rust-anstyle-1.0.14
    rust-anstyle-parse-1.0.0
    rust-anstyle-query-1.1.5
    rust-anstyle-wincon-3.0.11
    rust-anyhow-1.0.103
    rust-approx-0.5.1
    rust-arc-swap-1.7.1
    rust-arrayvec-0.7.7
    rust-async-io-2.6.0
    rust-atomic-0.6.1
    rust-atomic-polyfill-1.0.3
    rust-atomic-waker-1.1.2
    rust-autocfg-1.5.0
    rust-aws-lc-rs-1.17.0
    rust-aws-lc-sys-0.41.0
    rust-axum-0.8.9
    rust-axum-core-0.5.5
    rust-base64-0.22.1
    rust-basic-udev-0.1.2
    rust-bincode-2.0.1
    rust-bincode-derive-2.0.1
    rust-bitfield-0.19.4
    rust-bitfield-macros-0.19.4
    rust-bitflags-1.3.2
    rust-bitflags-2.13.0
    rust-bitmatch-0.1.1
    rust-bitvec-1.1.1
    rust-block-buffer-0.10.4
    rust-block-buffer-0.12.0
    rust-boolean-expression-0.3.11
    rust-bs58-0.5.1
    rust-bumpalo-3.19.1
    rust-by-address-1.2.1
    rust-bytemuck-1.24.0
    rust-bytemuck-derive-1.10.2
    rust-byteorder-1.5.0
    rust-bytes-1.11.1
    rust-bytesize-2.4.2
    rust-camino-1.2.2
    rust-capstone-0.14.0
    rust-capstone-sys-0.18.0
    rust-cargo-config2-0.1.44
    rust-cargo-platform-0.3.2
    rust-cargo-metadata-0.23.1
    rust-castaway-0.2.4
    rust-cbor-edn-0.0.6
    rust-cc-1.2.50
    rust-cfg-if-1.0.4
    rust-cfg-aliases-0.2.1
    rust-chacha20-0.10.1
    rust-chrono-0.4.42
    rust-clap-4.6.2
    rust-clap-builder-4.6.2
    rust-clap-complete-4.6.7
    rust-clap-derive-4.6.1
    rust-clap-lex-1.0.0
    rust-cmake-0.1.58
    rust-cmsis-pack-0.7.2
    rust-cobs-0.3.0
    rust-cobs-0.5.1
    rust-colorchoice-1.0.4
    rust-colored-2.2.0
    rust-colored-3.1.1
    rust-combine-4.6.7
    rust-compact-str-0.9.0
    rust-concurrent-queue-2.5.0
    rust-console-0.16.4
    rust-const-oid-0.10.2
    rust-convert-case-0.10.0
    rust-cordyceps-0.3.4
    rust-core-foundation-0.10.1
    rust-core-foundation-sys-0.8.7
    rust-cpp-demangle-0.5.1
    rust-cpufeatures-0.2.17
    rust-cpufeatures-0.3.0
    rust-crc32fast-1.5.0
    rust-critical-section-1.2.0
    rust-crossbeam-channel-0.5.15
    rust-crossbeam-utils-0.8.21
    rust-crossterm-0.29.0
    rust-crossterm-winapi-0.9.1
    rust-crypto-common-0.1.7
    rust-crypto-common-0.2.1
    rust-csv-1.4.0
    rust-csv-core-0.1.13
    rust-darling-0.20.11
    rust-darling-core-0.20.11
    rust-darling-macro-0.20.11
    rust-data-encoding-2.9.0
    rust-data-encoding-macro-0.1.18
    rust-data-encoding-macro-internal-0.1.16
    rust-debugid-0.8.0
    rust-deflate64-0.1.10
    rust-defmt-decoder-1.1.0
    rust-defmt-json-schema-0.1.0
    rust-defmt-parser-1.0.0
    rust-deku-0.18.1
    rust-deku-derive-0.18.1
    rust-deranged-0.5.8
    rust-derive-more-2.1.1
    rust-derive-more-impl-2.1.1
    rust-diff-0.1.13
    rust-digest-0.10.7
    rust-digest-0.11.2
    rust-directories-6.0.0
    rust-dirs-sys-0.5.0
    rust-displaydoc-0.2.5
    rust-dissimilar-1.0.10
    rust-docsplay-0.1.3
    rust-docsplay-macros-0.1.2
    rust-document-features-0.2.12
    rust-dunce-1.0.5
    rust-either-1.15.0
    rust-embedded-io-0.4.0
    rust-embedded-io-0.6.1
    rust-encode-unicode-0.3.6
    rust-encode-unicode-1.0.0
    rust-encoding-rs-0.8.35
    rust-env-filter-2.0.0
    rust-env-logger-0.11.11
    rust-equivalent-1.0.2
    rust-errno-0.3.14
    rust-escape8259-0.5.3
    rust-esp-idf-part-0.6.0
    rust-espflash-4.5.0
    rust-fallible-iterator-0.3.0
    rust-fast-srgb8-1.0.0
    rust-fastrand-2.4.1
    rust-figment-0.10.19
    rust-find-msvc-tools-0.1.5
    rust-flate2-1.1.9
    rust-fnv-1.0.7
    rust-foldhash-0.2.0
    rust-form-urlencoded-1.2.2
    rust-fs-extra-1.3.0
    rust-funty-2.0.0
    rust-futures-0.3.32
    rust-futures-channel-0.3.32
    rust-futures-core-0.3.32
    rust-futures-executor-0.3.32
    rust-futures-io-0.3.32
    rust-futures-lite-2.6.1
    rust-futures-macro-0.3.32
    rust-futures-sink-0.3.32
    rust-futures-task-0.3.32
    rust-futures-util-0.3.32
    rust-fxprof-processed-profile-0.8.1
    rust-gdbstub-0.7.8
    rust-generator-0.8.8
    rust-generic-array-0.14.7
    rust-getrandom-0.2.16
    rust-getrandom-0.3.4
    rust-getrandom-0.4.3
    rust-gimli-0.29.0
    rust-gimli-0.32.3
    rust-gimli-0.34.0
    rust-git-version-0.3.9
    rust-git-version-macro-0.3.9
    rust-glob-0.3.3
    rust-goblin-0.10.7
    rust-gpiocdev-0.8.0
    rust-gpiocdev-uapi-0.7.0
    rust-hash32-0.2.1
    rust-hash32-0.3.1
    rust-hashbrown-0.16.1
    rust-hashbrown-0.17.0
    rust-heapless-0.7.17
    rust-heapless-0.8.0
    rust-heapless-0.9.2
    rust-heck-0.5.0
    rust-hermit-abi-0.5.2
    rust-hex-0.4.3
    rust-hexdump-0.1.3
    rust-hexfloat2-0.1.3
    rust-hidapi-2.6.6
    rust-http-1.4.0
    rust-http-body-1.0.1
    rust-http-body-util-0.1.3
    rust-httparse-1.10.1
    rust-httpdate-1.0.3
    rust-hybrid-array-0.4.10
    rust-hyper-1.8.1
    rust-hyper-rustls-0.27.7
    rust-hyper-util-0.1.19
    rust-iana-time-zone-0.1.64
    rust-iana-time-zone-haiku-0.1.2
    rust-icu-collections-2.1.1
    rust-icu-locale-core-2.1.1
    rust-icu-normalizer-2.1.1
    rust-icu-normalizer-data-2.1.1
    rust-icu-properties-2.1.2
    rust-icu-properties-data-2.1.2
    rust-icu-provider-2.1.1
    rust-ident-case-1.0.1
    rust-idna-1.1.0
    rust-idna-adapter-1.2.1
    rust-ihex-3.0.0
    rust-indexmap-2.14.0
    rust-indicatif-0.18.6
    rust-indoc-2.0.7
    rust-inlinable-string-0.1.15
    rust-insta-1.48.0
    rust-instability-0.3.10
    rust-io-kit-sys-0.4.1
    rust-io-kit-sys-0.5.0
    rust-ioctl-sys-0.8.0
    rust-ipnet-2.11.0
    rust-iri-string-0.7.9
    rust-is-terminal-polyfill-1.70.2
    rust-itertools-0.9.0
    rust-itertools-0.13.0
    rust-itertools-0.14.0
    rust-itertools-0.15.0
    rust-itm-0.9.0-rc.1
    rust-itoa-1.0.16
    rust-jep106-0.3.0
    rust-jiff-0.2.23
    rust-jiff-static-0.2.23
    rust-jni-0.22.4
    rust-jni-macros-0.22.4
    rust-jni-sys-0.4.1
    rust-jni-sys-macros-0.4.1
    rust-jobserver-0.1.34
    rust-js-sys-0.3.83
    rust-kasuari-0.4.11
    rust-lazy-static-1.5.0
    rust-libc-0.2.186
    rust-libm-0.2.16
    rust-libredox-0.1.11
    rust-libtest-mimic-0.8.2
    rust-libyaml-rs-0.3.0
    rust-line-clipping-0.3.5
    rust-linkme-0.3.36
    rust-linkme-impl-0.3.36
    rust-linux-raw-sys-0.12.1
    rust-litemap-0.8.1
    rust-litrs-1.0.0
    rust-lock-api-0.4.14
    rust-log-0.4.33
    rust-loom-0.7.2
    rust-lru-0.18.0
    rust-lru-slab-0.1.2
    rust-lzma-rust2-0.16.2
    rust-mach2-0.4.3
    rust-mach2-0.5.0
    rust-maitake-sync-0.2.2
    rust-managed-0.8.0
    rust-matchers-0.2.0
    rust-matchit-0.8.4
    rust-md-5-0.10.6
    rust-md-5-0.11.0
    rust-memchr-2.7.6
    rust-memmap2-0.9.9
    rust-miette-7.6.0
    rust-miette-derive-7.6.0
    rust-mime-0.3.17
    rust-minimal-lexical-0.2.1
    rust-miniz-oxide-0.8.9
    rust-mio-1.2.0
    rust-mutex-traits-1.0.1
    rust-mycelium-bitfield-0.1.5
    rust-nix-0.26.4
    rust-nix-0.29.0
    rust-nix-0.30.1
    rust-nix-0.31.3
    rust-no-std-io2-0.8.1
    rust-nom-7.1.3
    rust-nu-ansi-term-0.50.3
    rust-num-bigint-0.4.6
    rust-num-conv-0.2.2
    rust-num-integer-0.1.46
    rust-num-traits-0.2.19
    rust-num-threads-0.1.7
    rust-nusb-0.2.5
    rust-object-0.36.7
    rust-object-0.39.1
    rust-once-cell-1.21.3
    rust-once-cell-polyfill-1.70.2
    rust-openssl-probe-0.1.6
    rust-option-ext-0.2.0
    rust-palette-0.7.6
    rust-palette-derive-0.7.6
    rust-parking-2.2.1
    rust-parking-lot-0.12.5
    rust-parking-lot-core-0.9.12
    rust-parse-int-0.9.0
    rust-paste-1.0.15
    rust-pear-0.2.9
    rust-pear-codegen-0.2.9
    rust-peg-0.8.5
    rust-peg-macros-0.8.5
    rust-peg-runtime-0.8.5
    rust-percent-encoding-2.3.2
    rust-pin-project-1.1.10
    rust-pin-project-internal-1.1.10
    rust-pin-project-lite-0.2.16
    rust-pin-utils-0.1.0
    rust-pkg-config-0.3.32
    rust-plain-0.2.3
    rust-polling-3.11.0
    rust-portable-atomic-1.12.0
    rust-portable-atomic-util-0.2.4
    rust-postcard-1.1.3
    rust-postcard-derive-0.2.2
    rust-postcard-rpc-0.12.1
    rust-postcard-schema-0.2.5
    rust-potential-utf-0.1.4
    rust-powerfmt-0.2.0
    rust-ppv-lite86-0.2.21
    rust-pretty-assertions-1.4.1
    rust-proc-macro-crate-3.4.0
    rust-proc-macro2-1.0.106
    rust-proc-macro2-diagnostics-0.10.1
    rust-quinn-0.11.9
    rust-quinn-proto-0.11.14
    rust-quinn-udp-0.5.14
    rust-quote-1.0.46
    rust-r-efi-5.3.0
    rust-r-efi-6.0.0
    rust-radium-0.7.0
    rust-rand-0.9.4
    rust-rand-0.10.2
    rust-rand-chacha-0.9.0
    rust-rand-core-0.9.3
    rust-rand-core-0.10.1
    rust-ratatui-0.30.2
    rust-ratatui-core-0.1.2
    rust-ratatui-crossterm-0.1.2
    rust-ratatui-widgets-0.3.2
    rust-redox-syscall-0.5.18
    rust-redox-users-0.5.2
    rust-regex-1.13.1
    rust-regex-automata-0.4.16
    rust-regex-syntax-0.8.11
    rust-reqwest-0.12.28
    rust-reqwest-0.13.4
    rust-ring-0.17.14
    rust-rmp-0.8.14
    rust-rmp-serde-1.3.1
    rust-roxmltree-0.20.0
    rust-rustc-demangle-0.1.26
    rust-rustc-hash-2.1.1
    rust-rustc-version-0.4.1
    rust-rustix-1.1.4
    rust-rustls-0.23.42
    rust-rustls-native-certs-0.8.2
    rust-rustls-pki-types-1.13.2
    rust-rustls-platform-verifier-0.7.0
    rust-rustls-platform-verifier-android-0.1.1
    rust-rustls-webpki-0.103.13
    rust-rustversion-1.0.22
    rust-rustyline-async-0.4.9
    rust-ruzstd-0.8.2
    rust-ryu-1.0.21
    rust-same-file-1.0.6
    rust-sanitize-filename-0.6.0
    rust-schannel-0.1.28
    rust-schemafy-0.6.0
    rust-schemafy-core-0.6.0
    rust-schemafy-lib-0.6.0
    rust-scoped-tls-1.0.1
    rust-scopeguard-1.2.0
    rust-scroll-0.13.0
    rust-scroll-derive-0.13.1
    rust-security-framework-3.5.1
    rust-security-framework-sys-2.15.0
    rust-semver-1.0.28
    rust-serde-1.0.228
    rust-serde-core-1.0.228
    rust-serde-derive-1.0.228
    rust-serde-json-1.0.150
    rust-serde-path-to-error-0.1.20
    rust-serde-plain-1.0.2
    rust-serde-repr-0.1.20
    rust-serde-spanned-0.6.9
    rust-serde-spanned-1.1.1
    rust-serde-urlencoded-0.7.1
    rust-serde-with-3.21.0
    rust-serde-yaml-0.9.34+deprecated
    rust-serialport-4.9.0
    rust-sha1-0.10.6
    rust-sha1-0.11.0
    rust-sha2-0.10.9
    rust-sha2-0.11.0
    rust-sharded-slab-0.1.7
    rust-shlex-1.3.0
    rust-signal-hook-0.3.18
    rust-signal-hook-mio-0.2.5
    rust-signal-hook-registry-1.4.7
    rust-simd-adler32-0.3.8
    rust-simd-cesu8-1.1.1
    rust-simdutf8-0.1.5
    rust-similar-2.7.0
    rust-slab-0.4.11
    rust-smallvec-1.15.1
    rust-socket2-0.6.3
    rust-spidev-0.7.1
    rust-spin-0.9.8
    rust-ssmarshal-1.0.0
    rust-stable-deref-trait-1.2.1
    rust-static-assertions-1.1.0
    rust-strsim-0.11.1
    rust-strum-0.27.2
    rust-strum-0.28.0
    rust-strum-macros-0.27.2
    rust-strum-macros-0.28.0
    rust-subtle-2.6.1
    rust-svd-parser-0.14.9
    rust-svd-rs-0.14.12
    rust-svg-0.18.0
    rust-symlink-0.1.0
    rust-syn-1.0.109
    rust-syn-2.0.119
    rust-sync-wrapper-1.0.2
    rust-synstructure-0.13.2
    rust-tap-1.0.1
    rust-target-triple-1.0.0
    rust-tempfile-3.27.0
    rust-termcolor-1.4.1
    rust-termtree-1.0.0
    rust-test-case-3.3.1
    rust-test-case-core-3.3.1
    rust-test-case-macros-3.3.1
    rust-test-log-0.2.21
    rust-test-log-core-0.2.21
    rust-test-log-macros-0.2.21
    rust-textwrap-0.16.2
    rust-thingbuf-0.1.6
    rust-thiserror-1.0.69
    rust-thiserror-2.0.18
    rust-thiserror-impl-1.0.69
    rust-thiserror-impl-2.0.18
    rust-thread-local-1.1.9
    rust-time-0.3.53
    rust-time-core-0.1.9
    rust-time-macros-0.2.31
    rust-tinystr-0.8.2
    rust-tinyvec-1.10.0
    rust-tinyvec-macros-0.1.1
    rust-tokio-1.53.0
    rust-tokio-macros-2.7.0
    rust-tokio-rustls-0.26.4
    rust-tokio-tungstenite-0.29.0
    rust-tokio-tungstenite-0.30.0
    rust-tokio-util-0.7.18
    rust-toml-0.8.23
    rust-toml-1.1.3+spec-1.1.0
    rust-toml-datetime-0.6.11
    rust-toml-datetime-0.7.5+spec-1.1.0
    rust-toml-datetime-1.1.1+spec-1.1.0
    rust-toml-edit-0.22.27
    rust-toml-edit-0.23.10+spec-1.0.0
    rust-toml-parser-1.1.2+spec-1.1.0
    rust-toml-write-0.1.2
    rust-toml-writer-1.1.2+spec-1.1.0
    rust-tower-0.5.2
    rust-tower-http-0.6.8
    rust-tower-layer-0.3.3
    rust-tower-service-0.3.3
    rust-tracing-0.1.44
    rust-tracing-appender-0.2.5
    rust-tracing-attributes-0.1.31
    rust-tracing-core-0.1.36
    rust-tracing-log-0.2.0
    rust-tracing-serde-0.2.0
    rust-tracing-subscriber-0.3.23
    rust-trait-variant-0.1.2
    rust-try-lock-0.2.5
    rust-trybuild-1.0.118
    rust-tungstenite-0.29.0
    rust-tungstenite-0.30.0
    rust-twox-hash-2.1.2
    rust-typed-arena-2.0.2
    rust-typed-path-0.12.3
    rust-typenum-1.19.0
    rust-uf2-decode-0.2.0
    rust-uncased-0.9.10
    rust-unescaper-0.1.8
    rust-unicode-ident-1.0.22
    rust-unicode-linebreak-0.1.5
    rust-unicode-segmentation-1.12.0
    rust-unicode-truncate-2.0.0
    rust-unicode-width-0.1.14
    rust-unicode-width-0.2.0
    rust-unit-prefix-0.5.2
    rust-unsafe-libyaml-0.2.11
    rust-untrusted-0.9.0
    rust-unty-0.0.4
    rust-uriparse-0.6.4
    rust-url-2.5.8
    rust-urlencoding-2.1.3
    rust-utf8-iter-1.0.4
    rust-utf8parse-0.2.2
    rust-uuid-1.24.0
    rust-valuable-0.1.1
    rust-version-check-0.9.5
    rust-virtue-0.0.18
    rust-walkdir-2.5.0
    rust-want-0.3.1
    rust-wasi-0.11.1+wasi-snapshot-preview1
    rust-wasip2-1.0.1+wasi-0.2.4
    rust-wasm-bindgen-0.2.106
    rust-wasm-bindgen-futures-0.4.56
    rust-wasm-bindgen-macro-0.2.106
    rust-wasm-bindgen-macro-support-0.2.106
    rust-wasm-bindgen-shared-0.2.106
    rust-wasm-streams-0.4.2
    rust-web-sys-0.3.83
    rust-web-time-1.1.0
    rust-webpki-root-certs-1.0.7
    rust-webpki-roots-0.26.11
    rust-webpki-roots-1.0.4
    rust-winapi-0.3.9
    rust-winapi-i686-pc-windows-gnu-0.4.0
    rust-winapi-util-0.1.11
    rust-winapi-x86-64-pc-windows-gnu-0.4.0
    rust-windows-core-0.62.2
    rust-windows-implement-0.60.2
    rust-windows-interface-0.59.3
    rust-windows-link-0.2.1
    rust-windows-result-0.4.1
    rust-windows-strings-0.5.1
    rust-windows-sys-0.52.0
    rust-windows-sys-0.61.2
    rust-windows-targets-0.52.6
    rust-windows-aarch64-gnullvm-0.52.6
    rust-windows-aarch64-msvc-0.52.6
    rust-windows-i686-gnu-0.52.6
    rust-windows-i686-gnullvm-0.52.6
    rust-windows-i686-msvc-0.52.6
    rust-windows-x86-64-gnu-0.52.6
    rust-windows-x86-64-gnullvm-0.52.6
    rust-windows-x86-64-msvc-0.52.6
    rust-winnow-0.7.14
    rust-winnow-1.0.0
    rust-wit-bindgen-0.46.0
    rust-writeable-0.6.2
    rust-wyz-0.5.1
    rust-xshell-0.2.7
    rust-xshell-macros-0.2.7
    rust-yaml-serde-0.10.4
    rust-yansi-1.0.1
    rust-yoke-0.8.1
    rust-yoke-derive-0.8.1
    rust-zerocopy-0.8.54
    rust-zerocopy-derive-0.8.54
    rust-zerofrom-0.1.6
    rust-zerofrom-derive-0.1.6
    rust-zeroize-1.8.2
    rust-zerotrie-0.2.3
    rust-zerovec-0.11.5
    rust-zerovec-derive-0.11.2
    rust-zip-8.6.0
    rust-zlib-rs-0.6.0
    rust-zmij-1.0.2
    rust-zopfli-0.8.3
    rust-zstd-0.13.3
    rust-zstd-safe-7.2.4
    rust-zstd-sys-2.0.16+zstd.1.5.7
)))
